.github/workflows/build-application.yaml

As a developer, I want to build and test my commits when I push them to a feature branch
so that, I know that my changes are compiled and validated with unit tests.
Fixes #
* Closes #22 
**Checklist**

Add GitHub Action yaml file to trigger application build steps

---

.github/workflows/spotless-check.yml

Add a CI Test that checks that the spotless check passes, otherwise it will fail and recommend to run the following command:
```
./gradlew spotlessApply
```
Fixes #31 
Raised another PR with the same exact changes, but added another commit with a modification of style so to force the failure of the check.
see here:
https://github.com/hashgraph/hedera-block-node/pull/42
**Checklist**

CI Test Check for Style guidelines using Spotless plugin

---

.gitignore
server/build.gradle.kts
server/docker/.dockerignore
server/docker/Dockerfile
server/docker/README.md
server/docker/docker-build.sh
server/docker/docker-compose.yml
server/docker/update-env.sh

This PR adds the necessary files and changes for creating a docker image, and also adds the gradle tasks to create, start and stop the docker containers for the block node server.
Fixes #44 
**Checklist**

Dockerization of Block Node Server

---

.github/workflows/release-push-image.yaml

Add a GHA WF for release image publishing, a single WF for both integration and production docker image publishing
Fixes #45
**Checklist**

Release image publish

---

.gitignore
protos/src/main/protobuf/blockstream.proto
server/src/main/java/com/hedera/block/server/BlockStreamService.java
server/src/main/java/com/hedera/block/server/Constants.java
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/module-info.java
server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java

feat: Added Get Block

---

.github/workflows/pr-formatting.yaml

On a previous commit a Pr-formmating GHA WF was introduced to make sure that all PRs have at least one Assignee, Label and that Milestone is also set. As well as title check to follow `conventional-pr-tittle`
However, only the conventional-pr-tittle was working, with this fix, all the other checks are working aswell.
Also, we are adding a `codecov.yml` file to define the code coverage configuration desired for the project
Fixes #
**Checklist**

fix: assigne, label and milestone checks

---

.github/workflows/release-push-image.yaml

Dockerfile needs build-context distributions and build-arg Version in order to sucessfully build and work as expected.
Fixes #
**Checklist**

ci: Fix Image publish GHA WF to provide build-arg and build-context to dockerfile.

---

server/build.gradle.kts
server/docker/update-env.sh

Add a new gradle task to start the docker container in debug mode.
Fixes #
**Checklist**

build: Add a new gradle task to start the docker container in debug mode.

---

codecov.yml

Adding CodeCov yml file for overriding configurations that are for the project
Fixes #
**Checklist**

test: Override configs for CodeCov, using yml file at project root

---

server/docker/docker-compose.yml
server/docker/metrics/dashboards/block-node-server.json
server/docker/metrics/dashboards/provisioner.yaml
server/docker/metrics/datasources/datasources.yml
server/docker/metrics/prometheus.yml
server/docs/metrics.md
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/com/hedera/block/server/config/BlockNodeContextFactory.java
server/src/main/java/com/hedera/block/server/metrics/MetricsService.java
server/src/test/java/com/hedera/block/server/metrics/MetricsServiceTest.java

Added initial metrics dashboard and dev containers to the dev docker-compose stack, so it includes a preconfigured Grafana + Prometheus services, with provisioned dashboard on source.
Added documentation for metrics as well.
Fixes #96 
Fixes #94 
Fixes #85 
Fixes #93 

feat: Grafana Initial Dashboard and Dev Env for Metrics

---

.gitignore
README.md
server/src/main/java/com/hedera/block/server/BlockStreamService.java
server/src/main/java/com/hedera/block/server/Constants.java
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/com/hedera/block/server/config/BlockNodeConfigExtension.java
server/src/main/java/com/hedera/block/server/consumer/ConsumerConfig.java
server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
server/src/main/java/com/hedera/block/server/persistence/storage/FileUtils.java
server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReader.java
server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderBuilder.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterBuilder.java
server/src/main/java/module-info.java
server/src/test/java/com/hedera/block/server/BlockStreamServiceIT.java
server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemoverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterTest.java
server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
server/src/test/resources/app.properties
server/src/test/resources/test.app.properties

- Created the following config classes
- ConsumerConfig
- PersistenceStorageConfig
- Refactored Classes to use those config instead of Helidon config
- Simplified Classes that already had BlockNodeContext to use config from there directly
- Refactored and Simplified all related Unit Tests
- 
Fixes #98 
Fixes #99 
Fixes #33 
**Checklist**

refactor: configuration to use Platform SDK across all project

---

server/src/main/java/module-info.java

On a previous PR #101  we introduced Configuration Classes (Config Holders and owners) using the `Platform SDK` framework, however we removed from modules-info.java file the necessary exports, and this is an issue that is only happening on runtime, so CI checks did not catch it.
This PR fixes that by re-introducing them back.
Fixes #104 
**Checklist**

fix: fix config exports

---

charts/hedera-block-node/templates/deployment.yaml
charts/hedera-block-node/values.yaml
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/com/hedera/block/server/health/HealthService.java
server/src/main/java/com/hedera/block/server/health/HealthServiceImpl.java
server/src/main/java/module-info.java
server/src/test/java/com/hedera/block/server/health/HealthServiceTest.java

Adding Endpoints for Health
- Liveness
- Readiness
Added started completed log message as INFO.
Needed unit tests.
Fixes #67 
**Checklist**

feat: Health endpoints

---

.github/workflows/helm-charts.yaml
.github/workflows/smoke-test.yaml
server/src/main/java/com/hedera/block/server/Server.java
server/src/test/resources/get-block.sh
server/src/test/resources/smoke-test.sh

- Add a new CI that performs a Smoke-Test on the BlockNode Server
- Adds 2 new scripts that are leveraged in order to perform the smoke-test:
- get-block.sh
- smoke-test.sh
Fixes #109 
**Checklist**

test: Smoke test

---

server/src/test/resources/get-block.sh

Fix smoke test after PBJ Changes were merged and rebased to use new types
Needed to update the singleBlockRequest test to use the new types.
Fixes #
**Checklist**

test: Fix smoke test after PBJ Changes were merged and rebased

---

server/src/test/java/com/hedera/block/server/BlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java

The flaky test in the bug ticket succeeds 100% locally. The test failure in the ticket points to the test timing out before it can confirm the observer is called.
* I increased the testTimeout values to 1 sec
* I did a light refactor on the tests to get them aligned on using a common test timeout at the test suite level.
Fixes #139

fix: Increased testTimeouts to promote test success on GHA runners

---

gradle/modules.properties
settings.gradle.kts

* Upgraded Helidon from 4.0.11 to 4.1.0
* Upgraded `io.grpc` deps from 1.64.0 to 1.65.1
* Upgraded gradle protobuf plugin deps from 3.21.7 to 4.27.3
* Removed unnecessary mapping and redundant definitions.
Fixes #137 
**Checklist**

chore: upgraded Helidon and its deps to 4.1.0

---

server/src/main/java/com/hedera/block/server/BlockStreamService.java
server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
server/src/main/java/com/hedera/block/server/metrics/MetricsInjectionModule.java
server/src/main/java/com/hedera/block/server/metrics/MetricsService.java
server/src/main/java/com/hedera/block/server/metrics/MetricsServiceImpl.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
server/src/test/java/com/hedera/block/server/BlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/config/BlockNodeContextTest.java
server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
server/src/test/java/com/hedera/block/server/metrics/MetricsInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/metrics/MetricsServiceTest.java
server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java

MetricsService refactor to use an interface
Refactor for Dagger DI metricsService 
Fixes #141 
**Checklist**

refactor: MetricsService refactor to use an interface

---

charts/hedera-block-node/values.yaml
server/src/main/java/com/hedera/block/server/health/HealthService.java
server/src/main/java/com/hedera/block/server/health/HealthServiceImpl.java
server/src/test/java/com/hedera/block/server/health/HealthServiceTest.java
server/src/test/resources/smoke-test.sh

Refactor HealthService to use readyz and livez instead of liveness and readyness endpoints
Fixes #119 
**Checklist**

refactor: Healthz endpoints refactor

---

.github/workflows/release-automation.yaml
charts/hedera-block-node/Chart.yaml
docs/release.md
server/build.gradle.kts

- Adds documentation explaning the release process
- Adds Gradle task and script for bumping versions during release process
Fixes #79 
Fixes: #80
**Checklist**

ci: GitHub Actions `Release automation` WorkFlow

---

.github/workflows/release-automation.yaml

Uses the newly added GPG_KEY_CONTENTS, GPG_KEY_PASSPHRASE, and GH_ACCESS_TOKEN github actions secrets to enable the workflow to run.
**Related Issue(s)**:
Fixes: #235
Fixes: #229 
Testing:
See the [v99.99.99-draft workflow run](https://github.com/hashgraph/hedera-block-node/actions/runs/11247622943/job/31272540073) which completes successfully

ci: Update release-automation.yaml to enable completion

---

server/docker/docker-compose.yml
server/docker/metrics/dashboards/cAdvisor.json
server/docker/metrics/prometheus.yml

- Improving Grafana configuration to remove login and need to change admin user
- Added cAdvisor to Docker dev Stack to collect system metrics on host and containers
- Added cAdvisor to list of targets to scrap from prometheus instance of the stack
- Added a Dashboard for System Host and Container metrics visualization on grafana
Fixes #257 
**Checklist**

feat: cAdvisor Docker System Metrics and Dashboard for Dev Docker Stack

---

simulator/README.md
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorApp.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockStreamConfig.java
simulator/src/main/java/com/hedera/block/simulator/config/types/StreamingMode.java
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/BlockStreamConfigTest.java
simulator/src/test/java/com/hedera/block/simulator/config/types/StreamingModeTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/BlockAsDirBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/BlockAsFileBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/BlockAsFileLargeDataSetsTest.java

Improvements to how the simulator is able to stream to the BlockNode, this commit creates a StreamingMode enum, with 2 values, CONSTANT_RATE and MILLIS_PER_BLOCK.
CONSTANT_RATE is the streaming mode that we have been using, that streams a block item, then waits X amount of NS, then streams another blockItem.
MILLIS_PER_BLOCK, does a lot less thread interruptions, and has a more realistic behaviour, since is going to stream the whole block, as fast as it can, and then going to sleep for X-(time it took to stream) being X the target of block production, by default 1 block is produced each second, so it will attempt to stream 1 block per every 1000 ms, however if the block takes more than 1000 ms to stream, it wont sleep at all, but WARN of a potential issue.
Added …

feat: added MILLIS_PER_BLOCK Streaming mode to the simulator

---

.github/workflows/smoke-test.yaml
README.md
server/build.gradle.kts
server/docker/update-env.sh
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
server/src/main/java/com/hedera/block/server/mediator/MediatorConfig.java
server/src/main/java/com/hedera/block/server/notifier/NotifierConfig.java
server/src/main/resources/app.properties
server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
suites/build.gradle.kts

- make the default values in config records to be the production ones;
- the app.properties file should not be setting the production values, by default it should be empty, we should only set props there if we want to override the production defaults;
- when executing smoke tests, the config records should be with test values;
- explore options to achieve the result: **(1)** use env variables - does not seem to work as expected, the config dependency gets the vars via `System.getenv()` and it only shows case-sensitive keys, so adding a value like `mediator.ringBufferSize=1024` will result into not being visible in runtime, it seems to me to be inconsistent. **(2)** build the jar for the smoke tests with the `app.properties` from `src/test/resources` - this works, the file …

refactor: adjust configuration management and smoke test setup to support production config by default

---

docs/Protocol/README.md
docs/Protocol/publishBlockStream.md

* Added a new document in `docs/Protocol` for `publishBlockStream`.
* Included a first pass protocol definition.
* Note this is in general informal language; not Estelle, SDL, LOTOS,
or other highly formal language.
Fixes #120

docs: Add a protocol document for `publishBlockStream`

---

common/src/main/java/com/hedera/block/common/utils/ChunkUtils.java
server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java

- feedback left on previous PR that was pending
Fixes #288 
**Checklist**

feat: Improvements ChunkUtils

---

simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulator.java
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorApp.java
simulator/src/main/java/com/hedera/block/simulator/Constants.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockStreamConfig.java
simulator/src/main/java/com/hedera/block/simulator/config/types/SimulatorMode.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClient.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/mode/CombinedModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/ConsumerModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/PublisherModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/SimulatorModeHandler.java
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/BlockStreamConfigTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImplTest.java
simulator/src/test/java/com/hedera/block/simulator/mode/CombinedModeHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/mode/ConsumerModeHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/mode/PublisherModeHandlerTest.java
suites/src/main/java/com/hedera/block/suites/BaseSuite.java
suites/src/main/java/com/hedera/block/suites/grpc/negative/NegativeServerAvailabilityTests.java
suites/src/main/java/com/hedera/block/suites/persistence/positive/PositiveDataPersistenceTests.java

This PR aims mainly to make the maintanence and using of simulator (as test driver) easier. It moves away the implementation of the working modes and exposes only abstractions. So that all concrete implementations can be refactored (if needed), without the main application, knowing or caring about it. 
Main simulator app should only be responsible for starting the processes and nothing more. Wherther the simulator will work in publisher or consumer mode, or both is not responsibility of the main class.
Also adds E2E test for data persistence.
Fixes #239 
**Checklist**

feat: Move out concrete working implementation and add working modes

---

server/docker/docker-compose.yml
simulator/build.gradle.kts
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorApp.java
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorInjectionComponent.java
simulator/src/main/java/com/hedera/block/simulator/config/ConfigInjectionModule.java
simulator/src/main/java/com/hedera/block/simulator/config/SimulatorConfigExtension.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/metrics/MetricsInjectionModule.java
simulator/src/main/java/com/hedera/block/simulator/metrics/MetricsService.java
simulator/src/main/java/com/hedera/block/simulator/metrics/MetricsServiceImpl.java
simulator/src/main/java/com/hedera/block/simulator/metrics/SimulatorMetricTypes.java
simulator/src/main/java/module-info.java
simulator/src/main/resources/app.properties
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java
simulator/src/test/java/com/hedera/block/simulator/TestUtils.java
simulator/src/test/java/com/hedera/block/simulator/config/ConfigInjectionModuleTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImplTest.java
simulator/src/test/java/com/hedera/block/simulator/metrics/MetricsInjectionModuleTest.java
simulator/src/test/java/com/hedera/block/simulator/metrics/MetricsServiceTest.java

* Introduced the MetricsService into the simulator subproject
* Changed the docker-compose.yml to make the prometheus port internal only to the stack
* Added tests
Running simulator output now contains the total block item count:
```
INFO: Loading block: 000000000000000000000000000000000028.blk.gz
Oct 29, 2024 1:25:57 PM com.hedera.block.simulator.generator.BlockAsFileLargeDataSets getNextBlock
INFO: block loaded with items size= 13
Oct 29, 2024 1:25:57 PM com.hedera.block.simulator.grpc.PublishStreamGrpcClientImpl streamBlock
INFO: Total Block items sent: 374
Oct 29, 2024 1:25:57 PM com.hedera.block.simulator.grpc.PublishStreamObserver onNext
```
Fixes #314 
**Checklist**

feat: setup metrics in the simulator to report block items sent

---

simulator/src/main/java/com/hedera/block/simulator/grpc/GrpcInjectionModule.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamObserver.java
simulator/src/main/java/com/hedera/block/simulator/mode/PublisherModeHandler.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImplTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamObserverTest.java
simulator/src/test/java/com/hedera/block/simulator/mode/PublisherModeHandlerTest.java

This PR adds simple error handling mechanism in the publisher, when onError is invoked.
Fixes #315 
This change is probably a very first version of the error handling mechanism that we want to have. We'd probably want to add checks and do different things, depending on the error. But as we are still in the early stage, this will do for now.
**Checklist**

feat: add error handling in publisher

---

common/src/main/java/com/hedera/block/common/utils/FileUtilities.java
common/src/main/java/com/hedera/block/common/utils/MathUtilities.java
common/src/main/java/com/hedera/block/common/utils/Preconditions.java
common/src/main/java/com/hedera/block/common/utils/StringUtilities.java
common/src/test/java/com/hedera/block/common/CommonsTestUtility.java
common/src/test/java/com/hedera/block/common/utils/MathUtilitiesTest.java
common/src/test/java/com/hedera/block/common/utils/PreconditionsTest.java
server/src/main/java/com/hedera/block/server/mediator/MediatorConfig.java
server/src/main/java/com/hedera/block/server/notifier/NotifierConfig.java
server/src/test/java/com/hedera/block/server/mediator/MediatorConfigTest.java
server/src/test/java/com/hedera/block/server/notifier/NotifierConfigTest.java

Implement agreed upon changes from discussion #266 
Fixes #305 
**Checklist**
---

refactor: implement agreed upon changes based on discussion (#266)

---

.gitignore
common/src/main/java/com/hedera/block/common/utils/Preconditions.java
common/src/test/java/com/hedera/block/common/CommonsTestUtility.java
common/src/test/java/com/hedera/block/common/utils/PreconditionsTest.java
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorApp.java
simulator/src/main/java/com/hedera/block/simulator/config/data/StreamStatus.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClient.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamObserver.java
simulator/src/main/java/com/hedera/block/simulator/metrics/SimulatorMetricTypes.java
simulator/src/main/java/com/hedera/block/simulator/mode/CombinedModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/ConsumerModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/PublisherModeHandler.java
simulator/src/main/java/com/hedera/block/simulator/mode/SimulatorModeHandler.java
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/StreamStatusTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImplTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/PublishStreamObserverTest.java
simulator/src/test/java/com/hedera/block/simulator/metrics/MetricsServiceTest.java
simulator/src/test/java/com/hedera/block/simulator/mode/PublisherModeHandlerTest.java
suites/src/main/java/com/hedera/block/suites/BaseSuite.java
suites/src/main/java/com/hedera/block/suites/CustomThreadPoolExecutor.java
suites/src/main/java/com/hedera/block/suites/ErrorLoggingExecutor.java
suites/src/main/java/com/hedera/block/suites/grpc/GrpcTestSuites.java
suites/src/main/java/com/hedera/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java
suites/src/main/java/com/hedera/block/suites/grpc/positive/PositiveServerAvailabilityTests.java
suites/src/main/java/com/hedera/block/suites/persistence/positive/PositiveDataPersistenceTests.java

This PR adds new functionality aimed at making the simulator a better and more flexible test driver for E2E tests. It achieves this by:
- Adding a new StreamStatus data object, which collects and stores information about the recently published/consumed blocks, as well as the latest statuses.
- Exposing the necessary methods to make this usable in other modules, primarily the E2E Tests module.
- Adding a new E2E test that covers the positive scenario where the simulator sends blocks to the Block Node, which responds with the correct response.
- Adds a new CustomThreadPoolExecutor to handle simulator threads, for now I'm just handling thrown errors, but in the future we might extend, depending on our needs.
Fixes #186  …

test: Add E2E test and enhance simulator flexibility

---

.github/workflows/e2e-tests.yaml
.github/workflows/smoke-test.yaml
.gitignore
server/build.gradle.kts
server/docker/docker-build.sh
server/docker/docker-compose.yml
server/docker/update-env.sh
suites/build.gradle.kts
suites/src/main/java/com/hedera/block/suites/BaseSuite.java

Isolate `gradle` tasks to not go outside of the respective project's build root.
Fixes #299
- am I missing something?
**Checklist**

fix: gradle tasks from different subproject are not isolated

---

.github/workflows/helm-charts.yaml
charts/.gitignore
charts/hedera-block-node/Chart.yaml
charts/hedera-block-node/README.md
charts/hedera-block-node/dashboards/block-node-server.json
charts/hedera-block-node/dashboards/kubernetes-views-pods.json
charts/hedera-block-node/dashboards/node-exporter-full.json
charts/hedera-block-node/templates/NOTES.txt
charts/hedera-block-node/templates/deployment.yaml
charts/hedera-block-node/templates/grafana-dashboard-configmap.yaml
charts/hedera-block-node/templates/grafana-datasource.yaml
charts/hedera-block-node/templates/service.yaml
charts/hedera-block-node/templates/servicemonitor.yaml
charts/hedera-block-node/values.yaml
server/docker/metrics/dashboards/block-node-server.json
server/docker/metrics/dashboards/cAdvisor.json
server/docker/metrics/datasources/datasources.yml

Adds Prometheus, Grafana and default dashboard to Helm templates for installation on K8 Cluster alongside the Block-Node Server.
Fixes #115 
https://www.loom.com/share/681859e788c14ab69cda1c6f453d44b2?sid=07b41500-259b-4963-bb14-fb50401ce91c

feat: Kubernetes grafana setup

---

server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
server/src/main/java/com/hedera/block/server/pbj/PbjBlockAccessServiceProxy.java
server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
server/src/main/java/com/hedera/block/server/producer/NoOpProducerObserver.java
server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
server/src/test/java/com/hedera/block/server/grpc/BlockAccessServiceTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockAccessServiceProxyTest.java
settings.gradle.kts

* Added integration with PBJ fix #304 
Fixes PBJ ticket #304 
**Checklist**

fix: integrated PBJ error propagation

---

server/docs/configuration.md
server/src/main/java/com/hedera/block/server/BlockNodeApp.java
server/src/main/java/com/hedera/block/server/ServerConfig.java
server/src/main/java/com/hedera/block/server/config/BlockNodeConfigExtension.java
server/src/main/java/com/hedera/block/server/config/ConfigInjectionModule.java
server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
server/src/test/java/com/hedera/block/server/BlockNodeAppTest.java
server/src/test/java/com/hedera/block/server/ServerConfigTest.java
server/src/test/java/com/hedera/block/server/config/ConfigInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java

- Adding a new Config Class called ServerConfig for Server specific properties.
- Adding 2 new properties to the newly created ServerConfig, and mapping them for ENV override using the ServerMappedConfigSourceInitializer. maxMessageSizeBytes and port.
- Replacing the hardcoded values on the codebase with the new configurable properties from ServerConfig.
- Added the new configuration to the ConfigInjectionModule
- Created UT for testing the Config validations and restrictions.
- Added Test case for ConfigInjectionModule to retrieve the newly config object.
Fixes #344 
Fixes #345 
**Checklist**

feat: server properties configurable

---

charts/hedera-block-node/templates/deployment.yaml
charts/hedera-block-node/values.yaml

it became obvious that we needed to increase the resource requirements and to allow easy parametrization using the values.yaml files.
Fixes #115
**Checklist**

feat: allow block-node operators to easily set resource allocations to block-node deployment on k8 using helm chart

---

.github/workflows/release-push-image.yaml
charts/hedera-block-node/Chart.yaml
charts/hedera-block-node/README.md

- updated chart name to hedera-block-node-chart, in order to differentiate it from the image name hedera-block-node.
- Changed the workflow that publishes the helm chart to use ghcr.io instead of a gh-pages branch.
Fixes #256 
**Checklist**

build: update helm publish registry to `ghcr.io`

---

simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulatorApp.java
simulator/src/main/java/module-info.java
simulator/src/main/resources/logging.properties
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java

This PR adds logging configuration in the simulator, this way using logging.properties one can set the verbose
Fixes #377 
**Checklist**

feat: add logging configurability to the simulator

---

server/docker/metrics/dashboards/block-stream-simulator-consumer.json
server/docker/metrics/dashboards/block-stream-simulator-publisher.json
server/docker/metrics/dashboards/provisioner.yaml
server/docker/metrics/prometheus.yml
simulator/docs/quickstart.md
simulator/src/main/resources/app.properties
simulator/src/test/java/com/hedera/block/simulator/config/ConfigInjectionModuleTest.java

This PR adds Grafana dashboards for monitoring the Block Stream Simulator in both Publisher and Consumer modes, along with the necessary Prometheus configuration to support metric collection.
* Add Grafana dashboards for Publisher and Consumer metrics
* Update Prometheus configuration to differentiate metrics by instance type
* Add metrics documentation to simulator quickstart guide
Fixes #379 
**Checklist**

feat: Add Grafana dashboards for the Simulator

---

server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
simulator/build.gradle.kts
simulator/src/main/java/com/hedera/block/simulator/BlockStreamSimulator.java
simulator/src/main/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/test/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java

This PR makes the following changes:
- On the `server` side adds the following missing configs to the mapper:
- producer.type → PRODUCER_TYPE (default: "PRODUCTION")
- mediator.type → MEDIATOR_TYPE (default: "PRODUCTION")
- On the `simulator` side adds the following missing configs to the mapper:
- From GrpcConfig.java:
- grpc.serverAddress (default: "localhost")
- grpc.port (default: 8080)
- From BlockStreamConfig.java:
- blockStream.simulatorMode (default: "PUBLISHER")
- blockStream.delayBetweenBlockItems (default: 1_500_000)
- blockStream.maxBlockItemsToStream (default: 100_000)
- blockStream.streamingMode (default: "MILLIS_PER_BLOCK")
- blockStream.millisecondsPerBlock (default: 1000)
- blockStream.blockItemsBatchSize (default: 1000)
- From BlockGeneratorConfig.java: …

chore: Add missing config values to mapper

---

server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalFileReader.java
server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalFileReaderTest.java
server/src/test/java/com/hedera/block/server/util/PersistTestUtils.java

- adding reading logic to complement #281 
Fixes #349 
- what would be the best way to parse the block file, having a file input stream and calling readAllBytes does not seem like the best option, there are other (based on the api), but which one would be preferable?
**Checklist**

feat: new BlockReader implementation for block-as-file

---

server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
simulator/build.gradle.kts
simulator/src/test/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java

- make a test that will be able to:
- verify the correct usage and declaration of any configuration record
- proactively fail and notify when we have added a configuration that has not the matching environment variable mapping
Fixes #420 
**Checklist**

test: add automatic unit test detection of missing configuration to environment variable mapping

---

buildSrc/src/main/kotlin/com.hedera.block.conventions.gradle.kts

Due to some of the work related to build deterministic we lost the ability to check for missing javadocs when build or assemble
Fixes #
**Checklist**

fix: Restoring javadocs verification

---

simulator/src/main/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockStreamConfig.java
simulator/src/main/java/com/hedera/block/simulator/config/data/StreamStatus.java
simulator/src/main/java/com/hedera/block/simulator/grpc/impl/ConsumerStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/grpc/impl/ConsumerStreamObserver.java
simulator/src/main/java/com/hedera/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
simulator/src/main/java/com/hedera/block/simulator/grpc/impl/PublishStreamObserver.java
simulator/src/test/java/com/hedera/block/simulator/BlockStreamSimulatorTest.java
simulator/src/test/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/BlockStreamConfigTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/StreamStatusTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/impl/ConsumerStreamGrpcClientImplTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/impl/ConsumerStreamObserverTest.java
simulator/src/test/java/com/hedera/block/simulator/grpc/impl/PublishStreamObserverTest.java
suites/src/main/java/com/hedera/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java

This PR aims to resolve unbounded memory growth within the simulator, when running in consumer mode. It's was caused by the uncontrollable grow of the lastKnownStatuses list, when running in "high-speed" mode.
- Changed to ArrayDeque with predefined capacity.
- Added new blockStreamConfig called lastKnownStatusesCapacity, set to be 10 by default
Fixes #404 
Here is image of the heap size before the fix:
Here is image of the heap size after the fix:
**Checklist**

chore: Fix Simulator unbounded memory growth

---

server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
server/src/main/java/com/hedera/block/server/persistence/storage/compression/Compression.java
server/src/main/java/com/hedera/block/server/persistence/storage/compression/NoOpCompression.java
server/src/main/java/com/hedera/block/server/persistence/storage/compression/ZstdCompression.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalDirPathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockPathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalFileReader.java
server/src/main/java/com/hedera/block/server/persistence/storage/remove/BlockAsLocalDirRemover.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsLocalDirWriter.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsLocalFileWriter.java
server/src/test/java/com/hedera/block/server/grpc/BlockAccessServiceTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/compression/NoOpCompressionTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/compression/ZstdCompressionTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalDirPathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalDirReaderTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalFileReaderTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsLocalDirRemoverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsLocalDirWriterTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsLocalFileWriterTest.java

- add compression support for the reader
Fixes #350 
N/A
**Checklist**

feat: add compression mode support for BlockAsFileReader

---

.github/workflows/release-push-image.yaml

Follow up to #216 as it broke some steps on `main`.
The steps are only used on `main` and I was not aware of them.

ci: fix extract version steps

---

charts/hedera-block-node/templates/configmap-logging.yaml
charts/hedera-block-node/templates/deployment.yaml
charts/hedera-block-node/values.yaml
server/docker/Dockerfile
server/docker/docker-compose.yml
server/docker/logging.properties
server/docker/update-env.sh
server/src/main/java/com/hedera/block/server/Server.java
server/src/main/java/module-info.java

Improves logs by doing the several changes:
Docker Image
Helm Chart - K8 (Cloud Env)
Docker-Compose (Local Dev Env)
Fixes #445 
Fixes #444 
Fixes #443 
Example of how logs are looking now:
```
Picked up JAVA_TOOL_OPTIONS: -Djava.util.logging.config.file=/app/logs/config/logging.properties -Duser.timezone=UTC
2025-01-05 06:46:12 INFO    [com.hedera.block.server.Server main] Starting BlockNode Server 
2025-01-05 06:46:12 INFO    [com.hedera.block.server.producer.ProducerConfig <init>] Producer configuration producer.type: PRODUCTION 
2025-01-05 06:46:12 INFO    [com.hedera.block.server.ServerConfig <init>] Server configuration server.maxMessageSizeBytes: 4194304 
2025-01-05 06:46:12 INFO    [com.hedera.block.server.ServerConfig …
```

refactor: Logs improvements

---

.github/workflows/helm-charts.yaml
charts/hedera-block-node/Chart.yaml
charts/hedera-block-node/README.md
charts/hedera-block-node/templates/_helpers.tpl
charts/hedera-block-node/templates/grafana-datasource.yaml
charts/hedera-block-node/values.yaml

In order to access logs from grafana, create panels and alerts based on logs we need to export them using promtail + loki and add them as provisioned datasources into the already existing grafana instance included on the helm chart.
Also configures multiline log merging for promtail.
This PR adds that functionality.
Fixes #433 
**Checklist**

feat: Add Loki to Helm chart deployment

---

.github/workflows/release-push-image.yaml
charts/blockstream-simulator/.helmignore
charts/blockstream-simulator/Chart.yaml
charts/blockstream-simulator/README.md
charts/blockstream-simulator/templates/NOTES.txt
charts/blockstream-simulator/templates/_helpers.tpl
charts/blockstream-simulator/templates/configmap.yaml
charts/blockstream-simulator/templates/deployment.yaml
charts/blockstream-simulator/templates/secret.yaml
charts/blockstream-simulator/values.yaml
charts/hedera-block-node/Chart.yaml
charts/hedera-block-node/templates/configmap.yaml
charts/hedera-block-node/templates/deployment.yaml
charts/hedera-block-node/templates/grafana-dashboard-configmap.yaml
charts/hedera-block-node/templates/grafana-datasource.yaml
charts/hedera-block-node/templates/ingress.yaml
charts/hedera-block-node/templates/secret.yaml
charts/hedera-block-node/templates/service.yaml
charts/hedera-block-node/templates/serviceaccount.yaml
charts/hedera-block-node/templates/servicemonitor.yaml
charts/hedera-block-node/values.yaml
ct.yaml

Helm Chart for the BlockStream Simulator, to allow using the simulator in cloud infrastructure or any K8 Cluster. 
Fixes #438 
**Checklist**

feat: Simulator helm chart

---

.github/workflows/release-automation.yaml
build.gradle.kts
server/build.gradle.kts

The release automation workflow was broken due to PR for Build migration to Hiero gradle plugins, this fixes it the issue with the version not been passed along correctly to the gradle `bumpVersion` task
Fixes #496
**Checklist**

fix: Fix Release Automation Workflow

---

.github/release.yaml
.github/workflows/release-automation.yaml

Cherry-pick of #506 
removing the generate notes step, since it was creating a release_notes.md, that failed spotless check, but also not using the release.yaml template that the github repo is using to auto-generate notes. So the output was not the desired one.
Since task Create Github Release can also generateReleaseNotes, we are using that one, so we have a unified template and way for auto-generation of release notes.
Fixes #
**Checklist**

fix: Cherry pick release notes fix

---

.github/release.yaml
.github/workflows/release-automation.yaml

removing the generate notes step, since it was creating a release_notes.md, that failed spotless check, but also not using the release.yaml template that the github repo is using to auto-generate notes. So the output was not the desired one.
Since task `Create Github Release` can also generateReleaseNotes, we are using that one, so we have a unified template and way for auto-generation of release notes.
Fixes #
**Checklist**

fix: Fix Release by Fixing Release Notes due to failed spotless check on generated file release_notes.md

---

server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java
server/src/main/java/com/hedera/block/server/ack/AckHandlerInjectionModule.java
server/src/main/java/com/hedera/block/server/notifier/NotifierImpl.java
server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
server/src/main/java/com/hedera/block/server/service/ServiceStatus.java
server/src/main/java/com/hedera/block/server/service/ServiceStatusImpl.java
server/src/main/java/module-info.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerImplTest.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
suites/src/main/java/com/hedera/block/suites/persistence/positive/PositiveDataPersistenceTests.java

This PR covers the following 2 use cases:
1. When BN receives a block_number that is LESS than the expected number (Received < Expected)
2. When BN receives a block_number that is MORE than the expected number (Received > Expected)
3. When BN encounters fails to persist due to internal reasons
Fixes #535  
Fixes #533 
Fixes #534 
Missing fix 2 integration tests (currently disabled)
**Checklist**

feat: CN2BN Protocol Communication Part 2

---

common/build.gradle.kts
common/src/main/java/com/hedera/block/common/hasher/ConcurrentStreamingTreeHasher.java
common/src/main/java/com/hedera/block/common/hasher/Hashes.java
common/src/main/java/com/hedera/block/common/hasher/HashingUtilities.java
common/src/main/java/com/hedera/block/common/hasher/NaiveStreamingTreeHasher.java
common/src/main/java/com/hedera/block/common/hasher/StreamingTreeHasher.java
common/src/main/java/module-info.java
common/src/test/java/com/hedera/block/common/hasher/ConcurrentStreamingTreeHasherTest.java
server/src/main/java/com/hedera/block/server/verification/session/BlockVerificationSessionAsync.java
server/src/main/java/com/hedera/block/server/verification/session/BlockVerificationSessionBase.java
server/src/main/java/com/hedera/block/server/verification/session/BlockVerificationSessionSync.java
server/src/main/java/com/hedera/block/server/verification/signature/SignatureVerifierDummy.java
server/src/main/java/module-info.java
server/src/test/java/com/hedera/block/server/verification/signature/SignatureVerifierDummyTest.java

This PR only moves the `hasher` subpackage of the `:server` subproject to the `:commons` subproject.
This so on a follow-up PR, we can implement the Generation Mode of the simulator with `valid` block_proof and hashes.
Fixes #569
**Checklist**

refactor: Move Hasher to `common` sub-project

---

server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java

Today during the demo it was found that there were some issues with the duplicate and future blocks. this was not evident during Unit Test, but when doing a `e2e` test it was found.
This PR fixes it.
Fixes #573 
**Checklist**

fix: issue with handling of `duplicate` and `future` blocks

---

server/docker/metrics/dashboards/block-node-server-logs.json

This PR  adds a dashboard to the docker compose stack (dev env) made of 3 log panel:
1. Config
2. Error or Severe
3. Warning
Fixes #434
**Checklist**

feat: Add Log Dashboard 

---

server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerImplTest.java

This PR adds test that helped replicate edge cases when acks were sent out of order.
either due to the workaround to determine the first valid block (where to start sending acks) or
due to random delays occur in either `persistence` or `verification` threads.
Also this PR includes the fixes so those tests always pass instead of always failing or sometimes failing.
Fixes #638
**Before:**
**After:** Under the same conditions, same result in multiple passes.

fix: ackHandler order responses under edge cases

---

server/src/main/java/com/hedera/block/server/consumer/AsyncConsumerStreamResponseObserver.java
server/src/main/java/com/hedera/block/server/consumer/ClosedRangeHistoricStreamEventHandlerBuilder.java
server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
server/src/main/java/com/hedera/block/server/consumer/Functions.java
server/src/main/java/com/hedera/block/server/consumer/HistoricBlockStreamSupplier.java
server/src/main/java/com/hedera/block/server/consumer/LiveStreamEventHandlerBuilder.java
server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediator.java
server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java
server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
server/src/main/java/com/hedera/block/server/mediator/MediatorInjectionModule.java
server/src/main/java/com/hedera/block/server/mediator/NoOpLiveStreamMediator.java
server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
server/src/main/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImpl.java
server/src/main/java/com/hedera/block/server/verification/StreamVerificationHandlerImpl.java
server/src/test/java/com/hedera/block/server/BlockNodeAppTest.java
server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
server/src/test/java/com/hedera/block/server/consumer/HistoricBlockStreamSupplierTest.java
server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
server/src/test/java/com/hedera/block/server/mediator/MediatorInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/notifier/NotifierImplTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImplTest.java
server/src/test/java/com/hedera/block/server/verification/StreamVerificationHandlerImplTest.java

* Changed the generics type from `SubscribeStreamResponseUnparsed` to `List<BlockItemUnparsed>`
* Removed `SubscribeStreamResponseUnparsed` processing logic from the verification, persistence and consumer subscribers.
Fixes #652

refactor: changed to batches of block items unparsed

---

.github/CODEOWNERS
.github/workflows/e2e-tests.yaml
.github/workflows/helm-charts.yaml
.github/workflows/pr-checks.yaml
.github/workflows/pr-formatting.yaml
.github/workflows/release-automation.yaml
.github/workflows/release-push-image.yaml
.github/workflows/smoke-test.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml
.github/workflows/zxc-verify-gradle-build-determinism.yaml

Updated the CODEOWNERS teams to reflect block node syntax Updated the self-hosted runners to use the new runner image: `hiero-block-node-linux-medium`
**Related Issue(s)**:
Fixes #667

ci: Updated CODEOWNERS and self hosted runners for hiero-block-node

---

server/docker/Dockerfile
server/docs/configuration.md
server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
server/src/main/java/com/hedera/block/server/persistence/storage/archive/BlockAsLocalFileArchiver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolver.java
server/src/main/resources/app.properties
server/src/test/java/com/hedera/block/server/config/ConfigInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
server/src/test/java/com/hedera/block/server/grpc/BlockAccessServiceTest.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsLocalFileReaderTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsLocalFileRemoverTest.java
server/src/test/java/com/hedera/block/server/util/PersistTestUtils.java

- change persistence config liveRootPath default to /opt/hashgraph/blocknode/data/live
- change persistence config archiveRootPath default to /opt/hashgraph/blocknode/data/archive
- both configs now use Path instead of String for their type
- docker user now has access to /opt
- change persistence config key archiveBatchSize to archiveGroup size for improved semantics (todo left from the past)
- config record no longer creates roots, it is just a value holder, it has no logic and is no decision maker
- remove deprecated usage of ConfigrationHolder (it also caused issues for tests)
- updated tests to pass with the new default paths
- updated documentation
Closes #371

chore: change the liverootpath and archiverootpath to absolute paths as default

---

simulator/build.gradle.kts
simulator/src/main/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockGeneratorConfig.java
simulator/src/main/java/com/hedera/block/simulator/config/types/GenerationMode.java
simulator/src/main/java/com/hedera/block/simulator/generator/CraftBlockStreamManager.java
simulator/src/main/java/com/hedera/block/simulator/generator/GeneratorInjectionModule.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/AbstractBlockItemHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/BlockHeaderHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/BlockProofHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/EventHeaderHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/EventTransactionHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/ItemHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/TransactionResultHandler.java
simulator/src/main/java/module-info.java
simulator/src/test/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/BlockStreamConfigTest.java
simulator/src/test/java/com/hedera/block/simulator/config/types/GenerationModeTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/BlockAsDirBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/CraftBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/GeneratorInjectionModuleTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/AbstractBlockItemHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/BlockHeaderHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/BlockProofHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/EventHeaderHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/EventTransactionHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/TransactionResultHandlerTest.java

With this PR we aim to introduce new generator mode for the block stream, by introducing new implementation for the `BlockStreamManager`. The following changes are included in this pull request:
- Addition of new `CraftBlockStreamManager` implementation with the purpose of crafting blocks on the fly and on demand. Currently we are adding random amount of items(transactions) in the block, according to the defined configuration.
- 4 new configuration properties for managing amount of block items in block
- `ADHOC` mode in `GenerationMode` renamed to `CRAFT`, to better explain the purpose and function of this mode.
- Handler for each type of introduced block item.
- `BlockHeaderHandler` responsible for crafting block header for each new block with needed fields.
- `BlockProofHandler` …

feat: simulator generation mode improvements

---

server/docker/logging.properties
simulator/build.gradle.kts
simulator/src/main/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockGeneratorConfig.java
simulator/src/main/java/com/hedera/block/simulator/config/types/GenerationMode.java
simulator/src/main/java/com/hedera/block/simulator/generator/CraftBlockStreamManager.java
simulator/src/main/java/com/hedera/block/simulator/generator/GeneratorInjectionModule.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/AbstractBlockItemHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/BlockHeaderHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/BlockProofHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/EventHeaderHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/EventTransactionHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/ItemHandler.java
simulator/src/main/java/com/hedera/block/simulator/generator/itemhandler/TransactionResultHandler.java
simulator/src/main/java/module-info.java
simulator/src/test/java/com/hedera/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
simulator/src/test/java/com/hedera/block/simulator/config/data/BlockStreamConfigTest.java
simulator/src/test/java/com/hedera/block/simulator/config/types/GenerationModeTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/BlockAsDirBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/CraftBlockStreamManagerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/GeneratorInjectionModuleTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/AbstractBlockItemHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/BlockHeaderHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/BlockProofHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/EventHeaderHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/EventTransactionHandlerTest.java
simulator/src/test/java/com/hedera/block/simulator/generator/itemhandler/TransactionResultHandlerTest.java

We need to include these 2 PRs as part of the `0.5.0` release, since they are needed for the **Long Term K8 Testing**
needed to release  a `0.5.0-rc2`

chore: Cherry picks for `0.5.0-rc2`

---

.github/workflows/pr-checks.yaml

This is the fix for CodeCov reports on open PRs.
**FINAL UPDATE:**
is working with @jjohannes suggestion 💯 
**Before:**
**After:** 🤞 
Try 2:

fix: CodeCov fix

---

server/docker/logging.properties
server/src/test/java/com/hedera/block/server/StackTracesTest.java

* Worked with @jsync-swirlds  to arrive at the logging format: `%TF %<TT.%<TL%<Tz %4$-7s [%2$s] %5$s%6$s%n`
Fixed #703

fix: changed the logging format and added tests

---

codecov.yml

Exclude `suites` and `tools` from CodeCov Coverage Report
Fixes #717

fix: Exclude `suites` and `tools` from CodeCov Coverage report

---

.github/workflows/zxc-verify-gradle-build-determinism.yaml

Update version of Ubuntu in the verify-artifacts job to be 24.04 and 22.04 instead of 22.04 and 20.04
**Related Issue(s)**:
Fixes #769

ci: Update ubuntu runners to 24.04 and 22.04

---

simulator/src/main/java/com/hedera/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
simulator/src/test/java/com/hedera/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java

1. Added test `testStreamBlock_RejectsAfterShutdown` to verify proper shutdown behavior:
- Verifies that client rejects new messages after shutdown
- Validates correct error message "Stream is already completed, no further calls are allowed"
- Added flag to prevent double shutdown in test teardown
2. Removed unnecessary sleep in `PublishStreamGrpcClientImpl.completeStreaming()`:
- Simplified the method to just call `onCompleted()`
- Removed redundant wait time that was causing potential delays
Fixes #352

chore: remove sleep on completeStreaming() in Simulator

---

.github/ISSUE_TEMPLATE/01-Story-Template.yml
.github/ISSUE_TEMPLATE/02-Epic-Template.yml
.github/ISSUE_TEMPLATE/03-Bug-Template.yml

* Added type to both forms
* Moved most values to placeholders
* Changed 3 separate questions to one text area for feature/task
* This improves readability versus the 3 separate headers github inserts
* Removed titles so that is entered more easily
* Fixed projects assignment
Small updates based on user feedback to make the template forms easier to use and less intrusive.

chore: Update issue templates

---

server/docs/configuration.md
server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
server/src/main/java/com/hedera/block/server/persistence/storage/write/AsyncWriterExecutorFactory.java
server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
server/src/test/java/com/hedera/block/server/config/logging/ConfigurationLoggingImplTest.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/write/AsyncWriterExecutorFactoryTest.java

This PR adds a configurable executor for async writers in the persistence storage module. The implementation allows for different executor types and configurations to optimize performance for various workloads and deployment environments.
- Added `ExecutorType` enum to `PersistenceStorageConfig` with options for `THREAD_POOL`, `SINGLE_THREAD`, and `FORK_JOIN` executors
- Added configuration properties for thread count, thread keep-alive time, virtual threads support, and execution queue limit
- Implemented `AsyncWriterExecutorFactory` to create appropriate executor instances based on configuration
- Updated `PersistenceInjectionModule` to use the factory for creating executors
- Added unit tests for all new components
- `persistence.storage.executionQueueLimit`: Maximum queue size for …

feat: allow for configuration of the async writers executors

---

.github/workflows/helm-charts.yaml
charts/block-node-server/templates/NOTES.txt
charts/block-node-server/templates/_helpers.tpl
charts/block-node-server/templates/configmap-logging.yaml
charts/block-node-server/templates/configmap.yaml
charts/block-node-server/templates/deployment.yaml
charts/block-node-server/templates/grafana-datasource.yaml
charts/block-node-server/templates/ingress.yaml
charts/block-node-server/templates/pvc-archive.yaml
charts/block-node-server/templates/pvc-live.yaml
charts/block-node-server/templates/secret.yaml
charts/block-node-server/templates/service.yaml
charts/block-node-server/templates/serviceaccount.yaml
charts/block-node-server/templates/servicemonitor.yaml
charts/block-node-server/values-overrides/mini.yaml
charts/block-node-server/values.yaml

- Fixed notes command for correct `port-forward` tunnel into the `block-node-server` using default port of `8080`
- changed all instances were resources were named with the `hedera` prefix and updated them for `hiero` prefix.
- Added Archive and Live PVC
- given flexibility to use existing external PVC instead of creating one.
- optimized `default` **Values.yaml** file for Production recommendations, and created a mini version that is intended to run on a minikube or similar environment for small tests.
- 
Fixes #793 
Fixes #792 
Fixes #791

feat: BN server Helm various improvements

---

server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java
server/src/main/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImpl.java
server/src/main/java/com/hedera/block/server/persistence/storage/archive/LocalGroupZipArchiveTask.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockPathResolver.java
server/src/main/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolver.java
server/src/main/java/com/hedera/block/server/service/ServiceStatus.java
server/src/main/java/com/hedera/block/server/service/ServiceStatusImpl.java
server/src/test/java/com/hedera/block/server/ack/AckHandlerImplTest.java
server/src/test/java/com/hedera/block/server/ack/AckHandlerInjectionModuleTest.java
server/src/test/java/com/hedera/block/server/manager/AckHandlerImplTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolverTest.java
server/src/test/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolverTest.java
simulator/src/main/java/com/hedera/block/simulator/config/data/BlockGeneratorConfig.java
simulator/src/main/resources/app.properties

- Changed the default start block generated from `1` to `0`
- Changed the assumption that Genesis block number was `1` on BN to `0`.
- Persistence will `traverse` the files and provide to `serviceStatus` the `lastBlock` persisted, so that BN can resume streaming from the last received block and not having to start always from genesis.
- Improved AckHandler init process due to now receiving the `lastAckedBlock` from persistence.
- Added UT with coverage for new functionality
The goal of this PR is to enable a simple and partial, but functional way for the BN to **Recover from restarts** so that persisted blocks are truly used and persisted across restarts.
Closes #796

feat: Simple Persistence startup data

---

.github/workflows/pr-formatting.yaml

Forked PRs were failing on title check. By setting `pull_request_target` the GHA can run in the needed context
Fixes #819

 chore: Set on pull_request_target for PR formatting check GHA

---

server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
server/src/test/java/com/hedera/block/server/util/BlockingExecutorService.java
server/src/test/java/com/hedera/block/server/util/TestUtils.java

- Added a custom BlockingExecutorService to ensure async logic in tests executes and completes before assertions begin.
- Used CountDownLatch technique to synchronize execution in cases where BlockingExecutorService cannot be properly injected.
- Modified PbjBlockStreamServiceProxy to enable custom executor injection for test purposes.
Fixes #642

chore: improvements for test repeatability

---

charts/block-node-server/templates/deployment.yaml
server/src/main/java/org/hiero/block/server/producer/ProducerBlockItemObserver.java
server/src/test/java/org/hiero/block/server/producer/ProducerBlockItemObserverTest.java

At the beginning of the sprint we decided to include a first/simple mechanism to recover from restarts, so that we can keep re-using `metrics, logs and data` from the next deployment forward. This meant adding a `Internal Memory` feature and Helm PVCs and its corresponding mappings and values so that both `archive` and `live` data were pesisted.
However, 3 bugs were found with the first `rc` version:
1. [Lost+Found directory present on created PVC](https://github.com/hiero-ledger/hiero-block-node/issues/815)
2. [PVC For Live and Archive Permissions](https://github.com/hiero-ledger/hiero-block-node/issues/816)
3. [Issue when restarted the BN](https://github.com/hiero-ledger/hiero-block-node/issues/814)
Fixes #815 
Fixes #816 
Fixes #814

fix: Various Bugs found on `0.6.0-rc1` deployment.

---

.github/workflows/e2e-tests.yaml
.github/workflows/pr-checks.yaml
.github/workflows/smoke-test.yaml

- update e2e-tests.yml, smoke-test.yml, and pr-checks.yml `on`-triggers to use pull_request: types per standard pull_request triggers.
**Related Issue(s)**:
Fixes #833

ci: Fix triggers for e2e-tests, smoke-test, and pr-checks

---

block-node/base/build.gradle.kts
block-node/base/src/main/java/module-info.java
block-node/server/src/main/java/module-info.java
common/src/main/java/module-info.java
settings.gradle.kts
simulator/src/main/java/module-info.java
stream/build.gradle.kts
stream/src/main/java/module-info.java
tools/build.gradle.kts

- Moved the base package for all modules to `org.hiero` in the main build settings
- Fixed all the references as needed (mostly just the "stream" module name changed).

chore: follow-up for hiero package move

---

charts/block-node-server/templates/deployment.yaml
charts/block-node-server/values-overrides/mini.yaml
charts/block-node-server/values.yaml

- Configuring all observability stack to use Persistent PVC instead of ephemeral disks.
- Set `subPath` for `archive-data` and `live-data` configurable via chart values.
- Added override for mini deployments
Fixes #831 
Fixes #847

feat: Configured Observability stack to use PVC on Helm Charts

---

block-node/base/src/main/java/org/hiero/block/server/ack/AckHandlerImpl.java
block-node/base/src/test/java/org/hiero/block/server/ack/AckHandlerImplTest.java

This issue was found on `0.6.0-rc2` after 233K blocks have been persisted, GCP restarted everything and the block-node was unable to recover sucessfully, while Persistence and Verification were continue to function properly, the ACK handler was initialized in a bad state.
Fixes #874

fix: restart recovery race condition

---

suites/src/main/java/module-info.java
suites/src/main/java/org/hiero/block/suites/BaseSuite.java
suites/src/main/java/org/hiero/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java
suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java

This PR:
- Enables all E2E tests that were previously disabled due to changes in the implementations.
- Modify and add additional startup method for the simulator, to allow flexible configuration changes.
Fixes #845 
Fixes #828

chore: Resolve and Enable E2E tests

---

block-node/base/src/main/java/module-info.java
block-node/base/src/main/java/org/hiero/block/server/persistence/PersistenceInjectionModule.java
block-node/base/src/main/java/org/hiero/block/server/utils/InjectionConstants.java
block-node/base/src/main/java/org/hiero/block/server/verification/StreamVerificationHandlerImpl.java
block-node/base/src/main/java/org/hiero/block/server/verification/VerificationInjectionModule.java
block-node/server/src/main/java/org/hiero/block/server/pbj/PbjBlockStreamServiceProxy.java

- Implemented named injection for StreamPersistenceHandlerImpl and StreamVerificationHandlerImpl.
- Scanned the project for similar cases but didn't find any. Other interfaces with multiple implementations rely on configuration-based injection managed by Dagger.
Closes #628

chore: named injection for components with a common interface

---

block-node/base/build.gradle.kts
block-node/messaging/build.gradle.kts
block-node/server/build.gradle.kts
common/src/main/java/module-info.java
common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
common/src/main/java/org/hiero/block/common/hasher/StreamingTreeHasher.java
simulator/build.gradle.kts
tools/build.gradle.kts

* Removed dependency from Common to swirlds-common that only provided 2 constants.
* Removed slf4j from build "runtime" dependencies.
* Verified that gradle checks do not require the dependency
Just a quick PR to remove an unused runtime dependency from the gradle build files.
This also cleans up an unnecessary dependency in the Common module.  Much as `com.swirlds.common` might seem basic from the name, it is actually a _very_ large module, with a vast dependency tree.
Fixes #870.

chore: Remove unneeded dependency on slf4j

---

block-node/app/docker/Dockerfile

This makes the docker related processes work and allows the app to run successfully inside a container along the rest of the stack.
However the `ccontainer image` created intentionally stayed the same/old name `block-node-server` instead of `block-node-app`, this decision was to unblock testing on docker while minimizing conflicts with the rest of the system.
In the future we can discuss if we want to rename the container image to `block-node-app` to keep consistency. 
in any case such a change would break, smoke tests, test suites, CI workflows (publish and release), local docker-compose env, observability integrations and possible more stuff.... so for now, I intentionally prefer to keep the name to `block-node-server` at the container image level. :)

Fixed Dockerfile to use new artifact name

---

block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
block-node/subscriber/src/main/java/org/hiero/block/node/subscriber/SubscriberServicePlugin.java

Previous to this fix, we were getting NOT FOUND status code from helidon.
Now connections are stablished and logic of consumer and publisher plugins is being executed.
Block-Node-App (Server)
Simulator on Publisher Mode
Simulator on Consumer Mode

Fixing GRPC Services Methods not found.

---

block-node/health/src/main/java/org/hiero/block/node/health/HealthServicePlugin.java
block-node/health/src/test/java/org/hiero/block/node/health/HealthServiceTest.java

New `HealthServicePlugin` was missing UTs and `HealthServiceTest` had UTs from prior to refactor that needed refactoring themselves
- Update `HEALTHZ_PATH` strings to be protected 
- Refactor lives and readyz tests in `HealthServiceTest` with mock considerations `BlockNodeContext` and `HealthFacility`
- Refactor testRouting test with capture logic to manage functional interface usage for HttpService to expose routes
Fixes #925

chore: Add HealthServicePlugin UTs

---

block-node/publisher/build.gradle.kts
block-node/publisher/src/main/java/module-info.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherConfig.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/UpdateCallback.java
block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java
block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherConfigTest.java

This PR aims to:
- Fix session handling of newly received items.
- Handle items where there are multiple items in the batch, including header in the beginning and proof at the end. 
- Plugin changes onSessionUpdate, where the session that called is chosen as primary and is handling whole block.
- Added unit tests for `PublisherConfig` and `BlockStreamProducerSession`.

fix: Publisher plugin fixes and tests

---

.github/workflows/pr-checks.yaml

Update PR Gradle Checks
- name to not be gradle specific
- `check-gradle` job to only run against main or release branches
- `compile` job name to make quality and UT run explicit
Addresses #951 
(will cherry pick down to main also)

chore: Improve PR Gradle Checks GHA definition in 505

---

charts/blockstream-simulator/templates/deployment.yaml

- Only adding PVC to mounting to container when deploying in Publisher Mode.
This can be cherry-picked and added to `rc2` then to `0.8.0` GA version.
Fixes #963

fix: Simulator Helm Chart Deployment in Consumer Mode

---

block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java

Add additional UTs for exception handling cases in BlockFileBlockAccessor
- Add nested depth test for additional `delete()` confidence
- Add logic to handle IOException and ParseException in block()
- Add logic to handle IOException and ParseException in blockUnparsed()
- Add logic to handle IOException in blockBytes() 
- Add logic to handle IOException in writeBytesTo() 
- Add logic to handle IOException in writeBytesTo() 
- Move shared setup logic from `createInstanceToTest()` into `buildAndCreateBlockAndGetAssociatedAccessor()` and `createBlockAndGetAssociatedAccessor()`
Fixes #969

chore: Add UTs for Recent BlockFileBlockAccessor exception handling

---

.github/workflows/local-node-test-reusable.yaml
.github/workflows/local-node-test.yaml

This PR adds a workflow that runs end to end tests using a local Hedera node setup. The workflow:
-  Builds our block-node Docker image from the current commit, to validate that there are no regressions.
-  Sets up the local-node environment with our built image.
-  Runs selected Hedera Smart Contracts tests and JSON-RPC Relay Acceptance tests. We are using only selected for two reasons:
a. To lower running time
b. We try to test and run transaction of different types. Most of the tests are running the same transactions.
-  Checks block-node logs for errors
The workflow runs on push to main/release branches and can be triggered manually. Also has option to select custom tags for CN, MN and Relay. Also to select custom branch to test for regressions.
Fixes #806 
Fixes #826

feat: Add E2E Local Node Smart Contracts Workflow

---

.github/workflows/local-node-test.yaml

Changing the GHA trigger to run only after a PR is merged to `main` since this one is taking `~40mins` and we don't need to run it that often.

ci: Change frequency of running LocalNode test GHA WF to just after merge

---

block-node/block-providers/files.historic/src/main/java/module-info.java
block-node/spi/src/main/java/org/hiero/block/node/spi/historicalblocks/LongRange.java
block-node/spi/src/test/java/org/hiero/block/node/spi/historicalblocks/LongRangeTest.java

This PR fixes the recently introduced LongRange class to take into consideration the case, when we pass start as -1 and end as -1. This means that we are starting on clean state with no blocks. Otherwise application throws exception and fails to load rest of the plugins.
```
Exception in thread "main" java.lang.IllegalArgumentException: Range start must be non-negative: -1
at org.hiero.block.node.spi@0.9.0-SNAPSHOT/org.hiero.block.node.spi.historicalblocks.LongRange.<init>(LongRange.java:32)
at org.hiero.block.node.base@0.9.0-SNAPSHOT/org.hiero.block.node.base.ranges.ConcurrentLongRangeSet.add(ConcurrentLongRangeSet.java:164)
at org.hiero.block.node.blocks.files.historic@0.9.0-SNAPSHOT/org.hiero.block.node.blocks.files.historic.BlocksFilesHistoricPlugin.init(BlocksFilesHistoricPlugin.java: …
```

fix: loading historic with clean state

---

block-node/base/build.gradle.kts
block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
block-node/block-providers/files.historic/build.gradle.kts
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockPath.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessor.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfigTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java

- this pr is semi-finished but has to merge in order to not stall further developments
- some more tests for the files historic plugin
- updated the BlockPath to be able to compute an existing path, adding the actual compression used on it (currently only naively checking for the extension)
- changes to the zip accessor were made to facilitate the block path updates, mainly to be able to correctly read (needs further testing, not asserting currently that it is 100% done, upcoming PRs will assert that)
Closes #990

test: Files Historic Plugin Unit Tests Pt 2

---

block-node/subscriber/src/main/java/org/hiero/block/node/subscriber/BlockStreamSubscriberSession.java
block-node/subscriber/src/test/java/org/hiero/block/node/subscriber/SubscriberTest.java

The test that is disabled needs more work to be correct.  It's passing _sometimes_ because it does not always reach a point to switch back to live blocks, and it's only succeeding when that happens.
We need to add a mechanism to the test historic block provider to better control how it behaves in the test so we can ensure the subscriber must switch to history (which already works) and _also_ reaches a point where it can switch back to live (which isn't there currently).

chore: Disabled an incomplete test.

---

block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
suites/src/main/java/module-info.java
suites/src/main/java/org/hiero/block/suites/BaseSuite.java
suites/src/main/java/org/hiero/block/suites/block/access/BlockAccessTestSuites.java
suites/src/main/java/org/hiero/block/suites/block/access/GetSingleBlockApiTests.java
suites/src/main/java/org/hiero/block/suites/grpc/positive/PositiveServerAvailabilityTests.java

- Added metrics port binding to BaseSuite
- Improvement on check for avaiable block at BlockAccessServicePlugin
- Fail fast when receiving both `retrieve_latest` and `block_number` on getSingleBlock Request to avoid bad DevEx and confusion
- since 0 is a valid block, we expect -1 when latest is set to true.
- Fixed UTs
- Added E2E Test Suite for Healthz and Metrics endpoints
- Added E2E Test Suite for GetSingleBlockAPI scenarios

feat: BlockAccessService E2E Tests Suite and other improvements to Plugin

---

simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java
simulator/src/main/java/org/hiero/block/simulator/config/types/MidBlockFailType.java
simulator/src/main/java/org/hiero/block/simulator/grpc/PublishStreamGrpcClient.java
simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
simulator/src/main/resources/app.properties
simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java

Mid-block sending failure can be triggered by setting blockStream.midBlockFailType and blockStream.midBlockFailOffset in app.properties. midBlockFailType takes NONE/ABRUPT/EOS as values. NONE is the default value which disables the feature. ABRUPT causes a runtime exception after sending the header and a random amount of items (without the proof). Currently, EOS (end of stream) causes calling of onError after sending the header and a random amount of items because PublishStreamRequest does not support end of stream messages, only a BlockItemSet.
midBlockFailOffset takes a numeric value and sets the amount on blocks to be sent before the failing block.
Test methods for the new functionality are added.
The streamBlockItem method is removed as it was redundant.
Closes #523

feat: added block stream simulator mid-block sending failure

---

block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
block-node/block-providers/files.historic/build.gradle.kts
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockPath.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java

- part 3 of unit tests for the files historic plugin
- some changes to the compress method for the ZSTD compression type for consistency with the wrapped stream method
- additional tests for the change in the compress method
Closes #1009

test: Files Historic Plugin Unit Tests Pt. 3

---

block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
block-node/block-providers/files.historic/build.gradle.kts
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockPath.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java

Force push erased the result, so re-running the same PR.

chore: Re-merge 1009 files historic plugin unit tests pt 3

---

.github/workflows/support/scripts/generate-gradle-artifact-baseline.sh

Adjusted the path and file(s) to generate the manifest to be the `app/build/distributions` folder and `tar` files instead of `server/build/libs` and `jar` files.
With multiple modules and plugins, the `tar` contains all the modules and dependencies; `libs` only contains the `app` module `jar` (and `server` doesn't exist, which is what caused the failure).

chore: Fix gradle baseline

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java

- part 4 of tests for the zip file
- reverted to using the static zstd compression method instead of streaming approach in our convenience implementation
- modified some tests so they can be more resilient
Closes #1021

test: Files Historic Plugin Unit Tests Pt. 4

---

block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java
suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java

- Due to Refactor to the `handlePersisted` method on `BlockStreamProducerSession` newer and faster publishing was not receiving ACKs, even when the BN did correctly switched to that publisher and the original (slower) publisher was correctly getting the acks (as it should)
- Fixed Other UT, since cannot longer start from 1, needs to start at 0.
Fixes #1033

fix: Fix e2e test after latest refactor

---

.github/workflows/release-push-image.yaml

- Updated internal version of docker/setup-buildx-action to fix cache deprecation issue by GitHub.
- replaced `build` for `assemble` to speed up the process, we only need assemble for this jobs and build was already done on previous job (deterministic check)
- Separated Publish of Block-Node-App and Simulator into its own Jobs, this was needed do to caching issues being reuseed from the first build failing with the 2nd build (simulator)
- Note: future work will complete decouple the simulator and block-node-app releases
Fixes issue: 
```
ERROR: failed to solve: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
```
Fixes #1041
take a look at this reference on how other teams fix it: 
Relay: …

fix: Fixing Publish Workflow

---

block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
suites/src/main/java/org/hiero/block/suites/BaseSuite.java
suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
suites/src/main/java/org/hiero/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java
suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java
suites/src/main/java/org/hiero/block/suites/utils/BlockSimulatorUtils.java
suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java

This PR resolves a case where, after hard shutdown of a producer the publisher stops accepting new producers.
Also moves around and cleans up the `suites`, by separating utils that can be used everywhere.
Fixes #1053 
Fixes #932

fix: hard shutdown of the producer causes exception when another is connected

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
block-node/stream-subscriber/build.gradle.kts
block-node/stream-subscriber/src/main/java/module-info.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberConfig.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
settings.gradle.kts

Adding a new plugin
* Instead of beating on the old implementation, implement a new subscriber plugin
that uses a single client thread and feeds that alternately from messaging or history
This avoids the countdown latch and state transition logic.
Also avoids a state machine, just take the next block from one source or the other,
always getting just the next block to send the client.
Does require a secondary queue from the messaging, but it's small and simple.
* Adjust the subscriber "method" class to be reused, so we track sessions properly
* Added a latch so the pipeline thread holds until the session is registered with
messaging before returning. This has minimal impact in production, and makes
it possible to test reliably.
* Added live block push to queue, live blocks stream …

feat: Create new stream subscriber plugin

---

simulator/src/main/java/org/hiero/block/simulator/config/ConfigInjectionModule.java
simulator/src/main/java/org/hiero/block/simulator/config/SimulatorConfigExtension.java
simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
simulator/src/main/java/org/hiero/block/simulator/config/data/UnorderedStreamConfig.java
simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
simulator/src/main/java/org/hiero/block/simulator/generator/GeneratorInjectionModule.java
simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublisherClientModeHandler.java
simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java
simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java
simulator/src/main/resources/app.properties
simulator/src/test/java/org/hiero/block/simulator/config/ConfigInjectionModuleTest.java
simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
simulator/src/test/java/org/hiero/block/simulator/config/data/UnorderedStreamConfigTest.java
simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
simulator/src/test/java/org/hiero/block/simulator/mode/PublisherClientModeHandlerTest.java
simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java

Implemented unordered block streaming in the simulator, configurable via app.properties.
The feature can be enabled by setting unorderedStream.enabled=true.
Two sub-modes are supported:
- Automatic Scrambling: Generates an unordered stream of blocks based on a specified block range and a scrambling coefficient.
- Fixed Sequence: Streams blocks in a predefined order specified in unorderedStream.fixedStreamingSequence.
Added unit tests to cover both sub-modes and the new configuration logic.
Closes #522

feat: added block stream simulator out-of-order streaming

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/BlockingSerialExecutor.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/NoOpServiceBuilder.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java

- Part 5 of tests for the `Files Historic` Plugin.
- We test the actual plugin here.
- Introduced a new blocking serial executor service for testing purposes that will allow us to serially execute tasks in the order they have been submitted, all on the caller thread, this ensure that tests will always be in assertable state and debugging is a breeze.
- Found a bug when merging a range in a ranged set, we allow the `LongRange` record to have -1 for start and end, but the merging logic does not allow that, which produces a runtime exception when we initialize a ranged set with `-1 -> -1` and then we try to add anything to it, for example if we add `0 - 9` to it, the ranged set will attempt to produce the following values `-1 -> 9` which the constructor of the `LongRange` record does not …

test: Files Historic Plugin Unit Tests Pt. 5

---

block-node/app/build.gradle.kts
block-node/stream-subscriber/build.gradle.kts
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSessionTest.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberConfigTest.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
suites/src/main/java/org/hiero/block/suites/subscriber/SubscriberTestSuites.java
suites/src/main/java/org/hiero/block/suites/subscriber/negative/NegativeSingleSubscriberTests.java
suites/src/main/java/org/hiero/block/suites/subscriber/positive/PositiveMultipleSubscribersTests.java
suites/src/main/java/org/hiero/block/suites/subscriber/positive/PositiveSingleSubscriberTests.java

This PR aim to:
- Introduce minor improvements to object checks, allocations and more.
- Add unit tests for config and session objects, with enough coverage and cases to ensure that we have adequte confidence in the plugin.
- Add E2E covering both negative and positive scenarios for single consumer cases and multiple consumer case.
- Fix issue, where we don't close the session and stop the streaming, when we execute succesfully the request.
- Enable new plugin as default.
Things to consider:
- One unit test disabled due to unstable behavior. Passes when run as standalone, fails when run with all others from the same class.
- Added check in method `allRequestedBlocksSent()` to ensure that when consumer requests 0 as end block, we continue to stream indefinitely.
- Added `close()` session …

test: Add subscriber plugin Tests

---

block-node/app/docker/Dockerfile

upgrading Java to 21.0.7+6 due to an issue with M4 Apple Silicon.
Related this this: https://github.com/hiero-ledger/solo/issues/1895
Using release from here:
https://github.com/adoptium/temurin21-binaries/releases
Fixes #1097

build(deps): upgrading Java to 21.0.7+6 due to an issue with M4 Apple Silicon.

---

block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java

- a wrongful precondition is causing the server to not be able to start
- the precondition must simply be flipped (it is a numeric comparison)
Fixes #1134

fix: BN is Unable to Restart due to `BlocksFilesHistoric` Plugin

---

docs/logging-guidelines.md

* Added logging-guidelines.md to the docs folder
* Filled in Purpose
* Filled in Level definitions
* Filled in recommended usage
* Filled in things to avoid
* Mangled formatting until Spotless would accept it
* Codacy still flags all definitions, though.
Resolves #1102

docs: Create a logging guidelines document

---

block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
protobuf/src/main/proto/org/hiero/block/api/block_access_service.proto
suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java

* Modified the proto definition to remove unverified and prevent calling with both latest and a block number.
* Added an "invalid" response and removed the verified/unverified responses
* Removed unnecessary prefixes in the response enum names
* Removed check for both fields set in Java (it's no longer possible).
* Fixed up all references
* Removed tests that set both fields as it's no longer possible (the last one set is the only one set).
Fixes #1148

fix: Adjust block access service to be correct without workarounds

---

block-node/app/docker/Dockerfile
block-node/app/docker/docker-compose.yml
block-node/app/docker/logging.properties
block-node/app/docker/update-env.sh
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfigTest.java
block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfig.java
charts/block-node-server/README.md
charts/block-node-server/templates/deployment.yaml
charts/block-node-server/templates/pvc-logging.yaml
charts/block-node-server/values-overrides/mini.yaml
charts/block-node-server/values.yaml
simulator/docker/Dockerfile
simulator/docker/update-env.sh
simulator/src/main/resources/logging.properties
suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java

Replaced /app with /opt in the server's Docker and Helm chart configurations, as well as in the simulator's Dockerfile.
Tested local run and Docker run for the server and the simulator.
Tested K8 run for the server.
P.S.
I was unable to test the simulator in K8 due to difficulties connecting it to a running BN server, likely because of a misunderstanding of the configuration steps on my part. While the simulator runs fine in a Docker container and chart changes were not applied, it would still be good to be tested.
A thorough review of these changes, especially regarding the K8 integration, would be greatly appreciated.
Closes #684

feat: changed container work dir from app to opt

---

block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
protobuf/src/main/proto/org/hiero/block/api/block_access_service.proto
suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java

Makes testers life easily of the `BlockAccessService` API.
Note: This is really not needed, it was found that `-1` in `uint64` can be sent using non-java tools as: `18446744073709551615` = `uint64_max`.
so payload request like:
```
{
"block_number": "18446744073709551615",
"retrieve_latest": true
}
```
Should work. 
But this PR would make that these would work:
```
{
"retrieve_latest": true
}
```
:)

chore: Cherry pick #1147 into `release/0.10` branch for `0.10.0-rc3` and final RC version.

---

block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java
protobuf/src/main/proto/org/hiero/block/api/block_stream_publish_service.proto
simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserver.java
simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserverTest.java

* Added the missing `EndStream` item for publish request
* Note, this does _not_ implement handling for this new message; it only adds the API definitions.
* Moved publish end stream code and response end stream code into their respective messages
* Removed `Acknowledgement` wrapper around `BlockAcknowledgement`.
* Removed unnecessary enum name prefixes
* Discovered another PBJ bug (unit tests generation) related to message name conflicts
* Fixed all references in code and tests
Fixes #1151

fix: Publisher API is missing some request forms

---

block-node/block-access/src/main/java/module-info.java
block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
protobuf/src/main/java/module-info.java

Stops exporting protoc to anything other than simulator and suites
Fixes #1088

fix: Moved GRPC services over to use PBJ generated ones

---

block-node/app/build.gradle.kts
block-node/server-status/build.gradle.kts
block-node/server-status/src/main/java/module-info.java
block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java
block-node/server-status/src/test/java/org/hiero/block/node/server/status/ServerStatusServicePluginTest.java
settings.gradle.kts
suites/src/main/java/org/hiero/block/suites/BaseSuite.java
suites/src/main/java/org/hiero/block/suites/server/status/ServerStatusTestSuites.java
suites/src/main/java/org/hiero/block/suites/server/status/positive/PositiveServerStatusTests.java
suites/src/main/java/org/hiero/block/suites/utils/ServerStatusUtils.java

This PR aims to:
- Create new plugin responsible for opening a unary endpoint for serving `ServerStatusRequest`.
- Handling of this requests is responsibility of the plugin, which returns:
```
message ServerStatusResponse {
uint64 first_available_block = 1;
uint64 last_available_block = 2;
bool only_latest_state = 3;
BlockNodeVersions version_information = 4;
}
```
- Add unit tests validating the correct behavior, using already existing test fixtures.
- Add E2E tests validating the behaviour of the endpoint.
Left out for next PRs:
- Handling of `only_latest_state` information, for now we just set it to false.
- Handling the construction of BlockNodeVersions object. We currently does not have this information at hand. Will require some change in order to be availble across the project. …

feat: create server status plugin

---

protobuf/src/main/java/module-info.java
simulator/docker/Dockerfile

- Fixed simulator container entry-point when executing start script.
- Fixed ability to Java usage of reflection from org.hiero.block.api.protoc to module com.google.protobuf. (this was only happening in docker and k8, due to IDE running everything using a single classpath)
Fixes #1173

fix: BlockStream Image Container broken

---

block-node/app/src/main/java/org/hiero/block/node/app/DefaultThreadPoolManager.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/TestThreadPoolManager.java
block-node/spi/src/main/java/org/hiero/block/node/spi/threading/ThreadPoolManager.java
block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java

* Added default implementations for reduced-call overloads.
* Adjusted both default and test implementations to clean up overloads
* Adjusted default implementation to handle null thread names
* Cleaned up JavaDoc and explained potential caching impacts.

chore: Clean up ThreadPoolManager API

---

.github/workflows/release-push-image.yaml

The package-block-node-protobuf jobs upload step succeeded but doesn't upload anything
Update path of upload to use `/protobuf`
Set if-no-files-found to error so we don't have silent failures
Fixes #1189

fix: Add protobuf path to artificat upload and fail on error

---

.github/workflows/release-push-image.yaml

The `package-block-node-protobuf` jobs upload step succeeded but doesn't upload anything
- Update path of uplaod to use `protobuf`
- Set `if-no-files-found` to `error` so we don't have silent failures
Partially addresses #1184

fix: (release/0.11) Add protobuf path to artificat upload and fail on error

---

protobuf/src/main/java/module-info.java

Cherry-pick of (#1191) into `release/0.11` so we can unblock complete testing workflows
Fixes #1190

fix: Opening for reflection, so Simulator can run in Consumer mode

---

protobuf/src/main/proto/org/hiero/block/api/block_stream_publish_service.proto

Minor fix to two response code enumeration names that aren't yet used.
Closes #1213

chore: Renamed two misnamed response code enumerations.

---

block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-node-service.json
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-historic.json
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-recent.json
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/stream-publisher.json
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/verification.json
block-node/app/docker/metrics/dashboards/block-node-server.json
block-node/block-providers/files.historic/build.gradle.kts
block-node/block-providers/files.historic/src/main/java/module-info.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
block-node/block-providers/files.recent/src/main/java/module-info.java
block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java
block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java
docs/block-node/metrics.md

- Added Metrics for Block.Provider **Files.Recent** Plugin.
- Added Grafana Dashboard for the above plugin.
- Added Metrics for BlockProvider **Files.Historic** Plugin
- Grafana Dashboard for Historic Provider Plugin
- Improved ServerStatus Metrics **server status** Plugin
- Grafana Dashboard for Server Status Metrics
- **Block-Node: Full-History** Dashboard as a Compact, most important Dashboard for a quick overview of the whole system.
- Bonus, Fixed/Improved naming of server status request and added it to the metrics document.
- Bonus 2, Fixed Metric (blockItemsReceivedCounter) on Messaging facility, was severely under-reeporting, was reporting batches, instead of block_items.
**Files.Recent**
**Files.Historic**
**Server Status**
**Block-Node: Full-History**
Fixes #1127 
Fixes #1128 …

feat: Add Metrics for Block-Providers Files.Recent, Files.Historic, Server Status and Summary Full History Dashboard

---

.github/ISSUE_TEMPLATE/03-Bug-Template.yml
protobuf-sources/src/main/proto/block-node/api/block_stream_subscribe_service.proto

* Fixed the proto spec for subscribe stream API
* Fixed a missing project value for the bug template.
Fixes #1259.

fix: #1259 fix protobuf spec to clarify that "infinite" is `uint64_max`.

---

docs/block-node/quickstart.md

Fix typos in quickstart markdown file
Original command "./gradlew :block-node:app:createDockerImage" lead to error
```
FAILURE: Build failed with an exception.
* What went wrong:
Cannot locate tasks that match ':block-node:app:createDockerImage' as project 'block-node' is ambiguous in root project 'hiero-block-node'. Candidates are: 'block-node-app', 'block-node-base', 'block-node-blocks-file-historic', 'block-node-blocks-file-recent', 'block-node-health', 'block-node-protobuf-pbj', 'block-node-protobuf-sources', 'block-node-s3-archive', 'block-node-server-status', 'block-node-spi-plugins', 'block-node-stream-publisher', 'block-node-stream-subscriber', 'block-node-verification'.
* Try:
> Run gradlew projects to get a list of available projects.
> For more on name expansion, please refer …
```

fix: typo in quickstart

---

.github/workflows/release-push-image.yaml
gradle/aggregation/build.gradle.kts

This will fix the currently broken _protobuf-sources_ publishing in the pipeline.
In contrast to other repositories (still using the `com.hedera` group) this change can be done now as the `org.hiero` group (used here) is already switched to the new publishing mechanism.
https://github.com/hiero-ledger/hiero-consensus-node/pull/19567

build: change publishing to use maven central publishing portal

---

tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/BlockAsFileBlockStreamManager.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/BlockAsFileLargeDataSets.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/BlockStreamManager.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/PublishStreamGrpcClient.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/SimulatorModeInjectionModule.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublisherClientModeHandler.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/BlockStreamSimulatorTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublisherClientModeHandlerTest.java

Add support in the block stream simulator, publisher mode, for receiving a EndOfStream message from the block node and correctly handling that response.
Fixes #1109

feat: Simulator Add Publisher Support for EndOfStream Message

---

settings.gradle.kts

This pull request includes a minor update to the `settings.gradle.kts` file, upgrading the `org.hiero.gradle.build` plugin from version `0.4.3` to `0.4.5`.
closes #1347

chore: Update gradle plugins to use 0.4.5

---

block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
docs/design/persistence/block-node-retention-policy.md

- updating the retention policy granularity setting to be zips retained rather than blocks retained
- this is easier to setup and less error prone
Resolves #1364

feat: Files Historic Plugin Retention Policy Granularity Update

---

block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/BlockStreamProducerSession.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherServicePlugin.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherTest.java
protobuf-sources/src/main/proto/block-node/api/block_stream_publish_service.proto
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java
tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java

Due to refactor efforts the block node had two forms to indicate a duplicate block PublishStreamResponse.end_stream.status.DUPLICATE_BLOCK` and ` PublishStreamResponse.acknowledgement.block_already_exists`
The latter response is no longer needed.
- Remove `block_already_exists` from `block_stream_publish_service.proto`
- Update `BlockStreamProducerSession.java` and `PublishStreamObserver.java` with updated `BlockAcknowledgment` message spec
- Update `PublisherTest.java` to have a test that reflects the `EndStream` as the source of block duplication notification to a publisher and not the Acknowledgment
- Remove `alreadyExists` logic from `SimulatorStartupData.java` and `SimulatorStartupDataImplTest.java` which was based on the `BlockAcknowledgment` message
- Fix …

chore: Remove the BlockAcknowledgement block_already_exists response

---

README.md
protobuf-sources/src/main/proto/block-node/api/block_access_service.proto
protobuf-sources/src/main/proto/block-node/api/block_stream_publish_service.proto
protobuf-sources/src/main/proto/block-node/api/block_stream_subscribe_service.proto
protobuf-sources/src/main/proto/block-node/api/proof_service.proto
protobuf-sources/src/main/proto/block-node/api/state_service.proto
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java

Standardize first 4 terminal code API responses
- Add to all terminal proto response message
- Update references to `INTERNAL_ERROR`
- Update README.md with references to Beta and HIP
- Move repo scorecard and shields links to top so it's more apparent for open source community 
Fixes #1399

chore: Standardize first 4 terminal code API responses

---

tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/data/BlockStreamConfigTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/data/UnorderedStreamConfigTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/types/GenerationModeTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/types/StreamingModeTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/BlockAsFileBlockStreamManagerTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcServerImplTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserverTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublisherServerModeHandlerTest.java

Currently, we have some tests in Sumulator that use imports with wildcards. Instead, all imports should explicitly specify the classes or static members they bring in.
Fixes #1401

test: Refactor wildcard imports in Simulator

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/PluginTestBase.java
block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java
block-node/server-status/src/test/java/org/hiero/block/node/server/status/ServerStatusServicePluginTest.java
block-node/stream-publisher/build.gradle.kts
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/StreamPublisherPluginTest.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
block-node/verification/src/test/java/org/hiero/block/node/verification/VerificationServicePluginTest.java

* Added unit tests:
* PublisherHandler:
* test onNext receives subsequent requests if previous one expected a header but did not receive
* tests for broken header supplied
* tests for null header bytes supplied
* test for sending acknowledgements
* tests for closeBlock called
* tests for handling block proof
* StreamPublisherPlugin:
* test for null items
* test for empty items
* test for unset oneOf
* test for valid block (disabled, finish in a follow up)
* Updated Publisher Manager test fixture:
* added implementation for handlePersisted
* added implementation for closeBlock
* added the ability to add a handler to send notifications to
* Extended Test Block Items Builder
* added the ability to create blocks with broken headers
* added the ability to create blocks with broken proofs
* …

test: Multi-Publisher Plugin Unit Tests - Interim PR

---

tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java

>At another test the BN was already with 23 blocks, and CN attempted to send block 0.
>BN responded with BEHIND, when we should have expected to respond with Duplicate Block.
Verifying that the bug is not reproducible with a test.
Closes #1449

test: add test for DUPLICATE_BLOCK status with starting block number 0

---

tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java

Setting the property `generator.endBlockNumber` prevents the simulator from continuing to stream blocks indefinitely.
Fixes #1459

fix: Setting property generator.endBlockNumber is not stopping simulator

---

tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserverTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java

Add support in the block stream simulator, publisher mode, for receiving a `ResendBlock` message from the block node and correctly resending that block then streaming following blocks after that as normal.
Fixes #840

feat:  Simulator add publisher support for ResendBlock message

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/server/TestBlockNodeServer.java
block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillConfiguration.java
block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillGrpcClient.java
block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillPlugin.java
block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
block-node/backfill/src/test/resources/block-nodes-2.json
block-node/backfill/src/test/resources/block-nodes-3.json
block-node/backfill/src/test/resources/block-nodes.json
block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java
block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockNotificationRingEvent.java
block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java
block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockMessagingFacility.java
block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockNotificationHandler.java
block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/NewestBlockKnownToNetworkNotification.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherManager.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java

- Added On-Demand Backfill flow
- Modified Backfill plugin to support both flows to run at the same time.
- Improved UTs to make them simpler and less repetitive, also improved reliability and all tests are 100% independent from one another.
- Added several new UTs related to Backfilling
- Allowed for partial chunks to be fetched instead of the complete batch (however this will required several scan iterations to complete a batch in certain scenarios)
- Added a new UT where a single gap has to be fetched from several BNs. 
- Modified publisherHandler to add capability to handle `TOO_FAR_BEHIND`, *EndStream* type message Request.
- Gave publisher MessagingFacility to be able to send Notifications. (minimal modifications of tests)
- Added missing metrics for new Block notifications types …

feat(backfill): On-Demand Backfilling and other improvements

---

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherManager.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManagerTest.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java

* Added handling for EndStream requests
* Added tests for end stream requests
* Improved shutdown logic to call onComplete
* Improved manager reliability when removing queues
* Disabled failing e2e test for on demand backfill
* Opened GH issue #1498 to tackle this
Closes #1236

feat: Add Support to Stream-Publisher for Handling `EndStream` Messages

---

block-node/app/docker/Dockerfile
block-node/app/docker/backfill-sources.json
block-node/app/docker/docker-compose.yml
block-node/app/docker/logging.properties
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/backfill.json
block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/messaging-facility.json
block-node/app/docker/metrics/dashboards/block-node-server.json
block-node/app/docker/update-env.sh
block-node/app/src/main/resources/logging.properties
charts/block-node-server/dashboards/Hiero-Block-Node-Plugins/backfill.json
charts/block-node-server/dashboards/Hiero-Block-Node-Plugins/messaging-facility.json
charts/block-node-server/values.yaml

- Created a New Dashboard specific for Backfill metrics
- backfill_gaps_detected
- backfill_blocks_fetched
- backfill_blocks_backfilled
- backfill_fetch_errors
- backfill_retries
- backfill_status
- backfill_pending_blocks
- Updated Messaging Dashboard with counters for new Notification types metrics
- messaging_block_backfilled_notifications
- messaging_newest_block_known_to_network_notifications
- Updated Full-History Dashboard with 2 new panels that come from Backfill
- Pending Blocks to Backfill
- Total Blocks Backfilled
- All of the above for both Docker and Chart dashboards provisioned.
- Made `TRACE`/`FINEST` logging level as default (we should revisit this after the BN is out of BETA phase)
- Due to the above I added some conditions to silence `TRACE` level logs that are coming …

feat(backfill): Adding Metrics Dashboards, improving logs by default and making backfill configuration easy on docker-compose stack

---

.github/workflows/pr-checks.yaml
block-node/protobuf-pbj/src/main/java/module-info.java
protobuf-sources/build.gradle.kts
tools-and-tests/protobuf-protoc/src/main/java/module-info.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/EventHeaderHandler.java
tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/SignedTransactionHandler.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/EventHeaderHandlerTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/SignedTransactionHandlerTest.java
tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
tools-and-tests/tools/src/main/java/org/hiero/block/tools/commands/BlockInfo.java
tools-and-tests/tools/src/main/java/org/hiero/block/tools/commands/ConvertToJson.java

CN proto was update to 0.65.0-rc1 and contains notable updates around TraceData and other items
- Bump CN proto to 0.65.0-rc1 in git clone gradle task
- Add export for `com.hedera.hapi.block.stream.trace` in `block-node/protobuf-pbj/src/main/java/module-info.java` to ensure classes are available
- Add export for  `com.hedera.hapi.block.stream.trace.protoc` to `tools-and-tests/protobuf-protoc/src/main/java/module-info.java` to ensure classes are available
Fixes #1386 
Fixes #1525
**Note for reviewers**
Once there's a 0.65.0 tag we can easily update the hash and there shouldn't be other changes but it's worthwhile to get this fixed to unblock testing with Solo
I'm still investigating the UT failure below. Can't seem to repro it locally 
```
* What went wrong:
Execution failed for task …
```

chore: Update CN proto to 0.65.0-rc1

---

.github/workflows/pr-checks.yaml
.github/workflows/release-push-image.yaml

Even if the source codebase is producing the correct version of protobuf sources, due to a hardcoded CN version of protobuf in the Release process, it was uploading an outdated one.
This can be remediated by uploading the correct ones to the release notes, and after this fix hopefully it will be parametrized  as should be.
Run it for release snapshot, and reviewed the output produced and is correct:
https://github.com/hiero-ledger/hiero-block-node/actions/runs/17142195576

fix(release): fix correct protobuf artifact publish

---

block-node/app/docker/update-env.sh
block-node/messaging/src/main/java/org/hiero/block/node/messaging/MessagingConfig.java
block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java
charts/block-node-server/values-overrides/mid-size.yaml
charts/block-node-server/values-overrides/mini.yaml
charts/block-node-server/values.yaml
docs/block-node/configuration.md

* Reduced default queue sizes for block items and block notifications.
* Notifications, in particular, need to be smaller, mostly because
blocks at high TPS can be 400M or larger.
* Adjusted values files for helm charts in the
base values, mini values, and mid-size values files.
* Automatic HPROF dump on error
* Added requested command line flags
May address #1523 and #1540.

fix(1523): Prevent Unexpected OutOfMemoryError under high load

---

block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java
common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
protobuf-sources/build.gradle.kts
protobuf-sources/src/main/proto/internal/unparsed.proto

- Update CN Proto to latest GA Tag
- Fixing verification hash by updating the unparsed.proto with the right Ids and names
Fixes #1569 
Fixes #1560 
Fixes #1522

fix(verification): Update CN Proto to latest GA Tag and Fix unparsed.proto file

---

block-node/app/docker/Dockerfile

* Added sudo to the oci image definition
* Added sudoers update to oci image definition
* Added a 30 day sleep after the block node exits abnormally
Resolves #1541
Resolves #1542

chore(1542): Add sudo and keep container active

---

charts/block-node-server/values-overrides/nano.yaml
charts/block-node-server/values.yaml

Sets all telemetry defaults to false as per recent meeting discussion. Telemetry dependencies have not been removed and have been kept around for dev testing purposes.
**Reference:** https://github.com/hiero-ledger/hiero-block-node/issues/1625

feat: Change telemetry defaults to false

---

settings.gradle.kts

⚠️ There is a silent breaking change in the **Gradle Shadow Plugin** update that came with `0.5.0` (see https://github.com/hiero-ledger/hiero-gradle-conventions/pull/300). As the plugin is used in this repository, please update asap.

build: bump Gradle plugins to 0.5.1

---

block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillConfiguration.java
block-node/messaging/src/main/java/org/hiero/block/node/messaging/MessagingConfig.java
charts/block-node-server/values-overrides/backfill.yaml
charts/block-node-server/values-overrides/mid-size.yaml
charts/block-node-server/values-overrides/mini.yaml
charts/block-node-server/values-overrides/nano.yaml

- As we noted on ticket https://github.com/hiero-ledger/hiero-block-node/issues/1576 we have sometimes a deadlock under certain circustances, even when there is another ticket to prevent that from happening, it makes sense to improve the default properties values and also con helm charts overrides to improve performance and minimize the risk of queues getting filled.

chore(config): Improve configs defaults and chart overrides regarding queueSize and backfillBatchSize

---

tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java

- Improving E2E test of combined backfill by not only increasing the amount of blocks that are going to be backfilled, but also by making it more resilient and flexible, getting rid of unnesary workarounds (delete files and restart a BN) since we did not had earliestManagedBlock property before
- adding better randomized verification
- adding a polling mechanism instead of hardcoded wait sleep times.
- Test takes around 40secs on M1 when previously used to take around 1 min and 20 secs (on the edge of timeout).
- increased the timeout to 2mins in case is run on slow hardware or the CI gets slow as it can happen.
Fixes #1707 
Currently E2E tests are a bit flakey since test might take longer on CI than timeout, this PR aims to fix this.

test(config): Improving Combined Backfill by Config

---

.github/workflows/helm-charts.yaml
.github/workflows/release-automation.yaml
.github/workflows/release-push-image.yaml
charts/block-node-server/values-overrides/enable-observability.yaml

- Makes new releases always in draft
- This allows the generated protobuf artifact to be automatically uploaded to the release notes
- adds observability stack enabled overlay.
Fixes #1733 
Fixes https://github.com/hiero-ledger/hiero-block-node/actions/runs/18330909151/job/52205573668?pr=1737

chore(release): Several Release Improvements and Fixes incluing auto-upload of proto artifact
