buildSrc/src/main/kotlin/com.hedera.block.jpms-modules.gradle.kts, server/src/main/java/module-info.java, settings.gradle.kts
Added needed dependencies on gradle files so we can use spotbug annotations like `@NonNull` or `@Nullable`
Fixes #86 
Fixes #30 
**Checklist**
=> feat: Add SpotBugs Annotation

server/build.gradle.kts
This is a follow up to:  PR #87 
Fixes #87
=> feat: added annotations for tests to use

settings.gradle.kts
Upgraded Helidon to 4.0.11
Helidon [4.0.11 release notes](https://github.com/helidon-io/helidon/blob/4.0.11/CHANGELOG.md)
=> chore: upgraded Helidon to 4.0.11

.github/CODEOWNERS, .github/workflows/pr-checks.yaml, .github/workflows/pr-formatting.yaml, .github/workflows/release-push-image.yaml
Updates the standard CODEOWNERS file
Updates the self hosted runners to conform to the latitude runners
Fixes #105
=> ci: update self hosted runner label and codeowners

.github/workflows/helm-charts.yaml
Updating our actions to pin full-length commit shas as checkout versions.
Fixes #176 
**Checklist**
=> ci: Updating actions to use full length commit sha.

.github/workflows/release-automation.yaml
Updating one github action step to step-security maintained version.
Fixes #301
=> ci: Updating workflow actions to step-security maintained version.

buildSrc/src/main/kotlin/com.hedera.block.spotless-java-conventions.gradle.kts
* Modified the gradle setup
* Ran a full spotlessApply; no change
=> chore: change spotless base format to Palantir plugin

server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java, server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java, server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java, server/src/test/java/com/hedera/block/server/grpc/BlockStreamServiceIntegrationTest.java, server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java, server/src/test/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImplTest.java, server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java, server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java, settings.gradle.kts, simulator/src/main/java/com/hedera/block/simulator/grpc/PublishStreamGrpcClientImpl.java, stream/build.gradle.kts
Updated the `hedera-protobuf` to the latest version on `main` that includes the most recent changes that affect the block-node. 
Use main commit: `1033f10` instead of temporary branch (with repeated block_items initial approach)
Fixes #302 
**Checklist**
=> refactor: Update protobuf to "latest" version

.github/workflows/release-automation.yaml
This PR aims to update the workflow action to the step-security maintained version.
Fixes #369
**Checklist**
=> chore: Updating action to step security maintained version.

server/docs/design/block-persistence.md
- revise the block persistence design doc
- extend the block persistence design doc to include specific implementations
Fixes #370 
N/A
**Checklist**
=> docs: add design docs for the block-as-file persistence

.github/workflows/release-push-image.yaml
Fixing a typo that is causing the publish to fail.
Fixes #
**Checklist**
=> fix: Fix Typo for publish of simulator helm chart

.github/workflows/release-automation.yaml, release_notes.md
As part of the release we are attempting to create a automatic `release_notes.md` for the release notes of the release, so we can also automate that process too. however this is not yet iron out, and with the addition of `md` files to the spotless, now the build was break. so we are fixing it manually, but also adding a fix to the pipeline.
Notes: The fix to the pipeline will also have to go into `main` but we have time and we rather do a single PR with possible more findings.
Fixes #
**Checklist**
=> fix: Stylefix release notes

server/docs/design/design-doc-template.md, server/docs/design/how-to-design-doc.md
* Added a short set of steps and a template markdown
Fixes #550 
**Checklist**
=> feat: added design doc template and short instructions

server/docs/design/design-doc-template.md
* Added Acceptance Tests section to the template based on feedback from @Nana-EC 
Fixes #550 
**Checklist**
=> fix: added an Acceptance Test section to the template

charts/hedera-block-node/dashboards/block-node-server.json, server/docker/metrics/dashboards/block-node-server.json, server/src/main/java/com/hedera/block/server/BlockNodeApp.java, server/src/main/java/com/hedera/block/server/ServerConfig.java, server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java, server/src/main/java/com/hedera/block/server/consumer/AsyncConsumerStreamResponseObserver.java, server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java, server/src/main/java/com/hedera/block/server/consumer/Functions.java, server/src/main/java/com/hedera/block/server/consumer/LiveStreamEventHandlerBuilder.java, server/src/main/java/com/hedera/block/server/events/BlockNodeEventHandler.java, server/src/main/java/com/hedera/block/server/mediator/MediatorConfig.java, server/src/main/java/com/hedera/block/server/metrics/BlockNodeMetricTypes.java, server/src/main/java/com/hedera/block/server/notifier/NotifierConfig.java, server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java, server/src/main/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImpl.java, server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java, server/src/main/java/com/hedera/block/server/verification/StreamVerificationHandlerImpl.java, server/src/main/java/com/hedera/block/server/verification/service/NoOpBlockVerificationService.java, server/src/test/java/com/hedera/block/server/BlockNodeAppTest.java, server/src/test/java/com/hedera/block/server/ServerConfigTest.java, server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java, server/src/test/java/com/hedera/block/server/config/logging/ConfigurationLoggingImplTest.java, server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java, server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java, server/src/test/java/com/hedera/block/server/verification/service/NoOpBlockVerificationServiceTest.java
* Added `AsyncConsumerStreamResponseObserver` injected with an `ExecutorService` to run the Callable `Functions.Task.call()` for each consumer created in `PbjBlockStreamServiceProxy`
* The current implementation of the `ExecutorService` is `Executors.newVirtualThreadPerTaskExecutor()` since it was the highest performing pooled Executor.
* Added new dashboard row called "Live Block Latency" to track how many blocks the live consumers are behind
* Added 2 new socket config properties to ServerConfig for experimental perf tuning later
* Refactored ServerConfig to leverage Preconditions
* Small change to `NoOpBlockVerificationService` to remain quiet when running in NO_OP mode
* Reduced the `mediator` RingBuffer default size. The `AsyncConsumerStreamResponseObserver` now …
=> feat: added async handling for live consumers

.github/ISSUE_TEMPLATE/01-Story-Template.yml, .github/ISSUE_TEMPLATE/02-Epic-Template.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
* Added an issue template configuration to allow blank issues
* Added an issue form for epics
* Added an issue form for agile stories (task or feature issues).
* Added a pull request template
=> chore: 275 add local issue templates for epic and task/feature

.github/ISSUE_TEMPLATE/01-Story-Template.yml, .github/ISSUE_TEMPLATE/02-Epic-Template.yml, .github/pull_request_template.md
* Issue forms put the `title` as a heading-3 for `textarea` fields
* Added the "closing" keywords to the pull request template.
=> fix: Adjusted issue forms to not double up headings

charts/hedera-block-node/dashboards/block-node-server.json, server/docker/metrics/dashboards/block-node-server.json, server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java, server/src/main/java/com/hedera/block/server/ack/AckHandlerInjectionModule.java, server/src/main/java/com/hedera/block/server/metrics/BlockNodeMetricTypes.java, server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java, server/src/test/java/com/hedera/block/server/manager/AckHandlerImplTest.java, server/src/test/java/com/hedera/block/server/manager/AckHandlerInjectionModuleTest.java, server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
This PR aims to add metrics for "acked" blocks.
=> feat: add Ack metrics

common/src/main/java/com/hedera/block/common/hasher/HashingUtilities.java, server/src/main/java/com/hedera/block/server/verification/session/BlockVerificationSessionSync.java, server/src/test/java/com/hedera/block/server/verification/session/BlockVerificationSessionBaseTest.java
This PR  fixes the Hash algorithm so verification can succeed after updates in services. 
Fixes #643
=> fix: Fixing Hashing Algorithm to match services

server/build.gradle.kts, settings.gradle.kts, simulator/build.gradle.kts, tools/build.gradle.kts
Includes:
- use `feature.shadow` and `feature.legacy-classpath` in `tools`
- updates dependency analysis plugin
- discovered unnecessary `requiresStatic` dependencies in "test" scope
- updates Spotless plugin (slight adjustments in Gradle file formatting)
=> build: update hiero-gradle-conventions to 0.3.4

hiero-dependency-versions/build.gradle.kts, stream/build.gradle.kts
=> chore: Upgrade PBJ to `0.9.17`

charts/hedera-block-node/dashboards/block-node-server.json, server/docker/metrics/dashboards/block-node-server.json, server/src/main/java/com/hedera/block/server/metrics/BlockNodeMetricTypes.java, server/src/main/java/com/hedera/block/server/persistence/storage/write/AsyncBlockAsLocalFileWriter.java
* Added a new row to the errors section of the dashboards to track block persistence errors
* Added ERROR logging if a block fails to persist successfully
Fixes #648
=> feat: added block persistence error dashboards and error logging

server/src/test/java/com/hedera/block/server/persistence/storage/write/AsyncBlockAsLocalFileWriterTest.java
* Fixed failing unit tests I broke with my last commit/merge
Related #670
=> fix: fixed broken unit tests from new metric

server/docs/design/historic-streaming/open-range-historic-streaming.md
* Added a design doc for open-range historic streaming blocks
Closes #488
=> feat: added design doc for open-range historic streaming blocks

.github/ISSUE_TEMPLATE/01-Story-Template.yml, .github/ISSUE_TEMPLATE/02-Epic-Template.yml
* Update the story template with correct project ID
* Update the epic template with correct project ID
* Remove tasklist rendering
* Remove the prefixes in issue titles
=> chore: Modify issue templates for new project

README.md
=> docs: Update README.md for Hiero

charts/block-node-server/README.md, charts/blockstream-simulator/README.md, docs/overview.md, server/README.md, server/docs/configuration.md, server/docs/design/block-persistence.md, server/docs/design/live-streaming/bidi-producer-consumers-streaming.md, server/docs/metrics.md, simulator/README.md
This PR aims to update all references to `hedera` in the documents for `hiero-ledger` 
This is the second PR.
Lefovers will be handled in a third and hopefully final PR.
Fixes #669
=> chore: Part 2 Hiero migration update docs

server/src/main/java/com/hedera/block/server/consumer/OpenRangeStreamManager.java, server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java, server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java, server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandlerBase.java, server/src/main/java/com/hedera/block/server/notifier/NotifierImpl.java, server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java, server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamRunnableTest.java, server/src/test/java/com/hedera/block/server/consumer/OpenRangeStreamManagerTest.java, server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java, server/src/test/java/com/hedera/block/server/notifier/NotifierImplTest.java, server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java, server/src/test/java/com/hedera/block/server/util/PbjProtoTestUtils.java
* Realigned disabled unit test to the new consumer polling mechanism
* Fixed broken Producer metric
Fixes #751
=> chore: fixed disabled tests

.github/workflows/e2e-tests.yaml, .github/workflows/pr-checks.yaml, .github/workflows/smoke-test.yaml, charts/block-node-server/templates/deployment.yaml, server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java, server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
This is a cherry-pick of #817 into `release/0.6` branch, in preparations for `0.6.0-rc2` release.
=> fix: Various Bugs found on `0.6.0-rc1` deployment. (Cherry-pick of #817 into `release/0.6` branch)

block-node/messaging/build.gradle.kts, block-node/messaging/src/main/java/module-info.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockItemHandler.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockNotification.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockNotificationHandler.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/MessagingService.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/NoBackPressureBlockItemHandler.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/BlockItemBatchRingEvent.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/BlockNotificationRingEvent.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/MessagingConfig.java, block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/MessagingServiceImpl.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockItemBatchRingEventTest.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceBlockItemTest.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceBlockNotificationTest.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceDynamicBlockItemTest.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceExceptionTest.java, settings.gradle.kts
=> feat: Add messaging module

server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java, server/src/test/java/com/hedera/block/server/ack/AckHandlerImplTest.java
This is a Cherry-pick of #875  into release branch `release/0.6` in preparation for `0.6.1` patch release.
=> chore: Cherry pick 875 into `release/0.6` branch

.github/workflows/e2e-tests.yaml, .github/workflows/helm-charts.yaml, .github/workflows/pr-checks.yaml, .github/workflows/pr-formatting.yaml, .github/workflows/release-automation.yaml, .github/workflows/release-push-image.yaml, .github/workflows/smoke-test.yaml, .github/workflows/zxc-verify-gradle-build-determinism.yaml
* Added time limits to most jobs
* Added ionice to most processor or I/O heavy steps.
Resolves #903
=> chore: Adjust workflows to reduce "stuck" jobs via reduced priority and time limits.

block-node/app/build.gradle.kts
=> chore: fix gradle build to use module path

block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java
* Several different changes attempted
* The problem is race conditions in the tests for "backpressure" and "everything
is delivered".
* Needed to rework those tests to set appropriate points where the test thread and the messaging thread can synchronize to ensure the test verifies what it needs to (that exceeding the messaging buffer limit causes the publishing to pause until it's cleared, and that handlers get all of the messages published).
* Adjusted all tests to use a separate thread for sending to prevent deadlock in the test thread
* Modified sending and handler code to inner classes instead of lambdas to reuse and ensure fixes applied to all cases
* Replaced sleep usage with `parkNanos` instead (avoids catch blocks and works equivalently for test code)
* Added or adjusted delays to …
=> chore: Fix unpredictable deadlocks in block notification tests

MAINTAINERS.md
Maintainers file added as described at https://lf-decentralized-trust.github.io/governance/governing-documents/MAINTAINERS-file.html
=> docs: Create MAINTAINERS.md

block-node/block-providers/files.recent/build.gradle.kts, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfig.java, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandler.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java, hiero-dependency-versions/build.gradle.kts
- unit tests for `Files Recent` plugin
- some cleanup && isolation improvements
Closes #942
=> test: Files Recent Plugin Unit Tests

block-node/block-providers/files.recent/build.gradle.kts, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessor.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java, common/build.gradle.kts, common/src/main/java/org/hiero/block/common/utils/Preconditions.java, common/src/test/java/org/hiero/block/common/utils/PreconditionsTest.java
- part 2 of unit tests for the `Files Recent` Plugin
Closes #946
=> test: Files Recent Plugin Unit Tests Pt.2

block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java, block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java, block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java
This PR adds publisher session handling for empty list, tests for it and some additional checks all around.
=> fix: Add empty list handling for Publisher Session

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandler.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java, block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java
- part 3 of unit tests for the files recent plugin
Closes #956 
Closes #957
=> test: Files Recent Plugin Unit Tests Pt.3

.github/workflows/smoke-test.yaml, suites/build.gradle.kts, suites/src/main/java/module-info.java, suites/src/main/java/org/hiero/block/suites/BaseSuite.java, suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
This PR fixes the E2E test suite and also fixes a technical debt regarding the coupling of the sub-projects
Fixes #343
=> fix: e2e improvements

.github/workflows/pr-checks.yaml, charts/blockstream-simulator/templates/deployment.yaml
Cherry-pick of #964 into `release/0.8` release branch.
Also picks #962 into `release/0.8` release branch.
=> fix: Simulator Helm Chart Deployment in Consumer Mode (#964)

block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java, block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java, block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java, block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java, block-node/spi/src/test/java/org/hiero/block/node/spi/historicalblocks/BlockAccessorTest.java, simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/BlockHeaderHandler.java, simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java, simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java, simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java, simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/BlockHeaderHandlerTest.java, simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java, simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java, stream/build.gradle.kts, tools/src/main/java/org/hiero/block/tools/commands/record2blocks/Record2BlockCommand.java
This PR makes some improvements for the Publisher plugin mainly. Some re-ordering and handling of multiple producers.
=> fix: more publisher improvements

.github/workflows/pr-formatting.yaml
Bumps version for step-security/conventional-pr-title-action
Fixes: 997
=> fix: Update pr-formatting.yaml

simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java, simulator/src/main/java/org/hiero/block/simulator/config/data/BlockGeneratorConfig.java, simulator/src/main/java/org/hiero/block/simulator/config/data/ConsumerConfig.java, simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java, simulator/src/main/resources/app.properties, suites/src/main/java/org/hiero/block/suites/verification/BlockVerificationTestSuites.java, suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java
WIP for Verification e2e Tests.
=> test: Verification e2e tests

simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java, simulator/src/main/java/org/hiero/block/simulator/config/data/BlockGeneratorConfig.java, simulator/src/main/java/org/hiero/block/simulator/config/data/ConsumerConfig.java, simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java, simulator/src/main/resources/app.properties, suites/src/main/java/org/hiero/block/suites/verification/BlockVerificationTestSuites.java, suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java
Force push erased the result, so re-running the same PR.
=> chore: Re-merge Verification e2e tests

.github/workflows/zxc-verify-gradle-build-determinism.yaml
* Fixed another incorrect/obsolete path entry
=> chore: Fix gradle determinism verification

simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java, simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
- simple updates to the awareness tests for the configurations and logging
Closes #1036
=> test: Failing UT for Simulator Config Mappings

.github/workflows/release-push-image.yaml
cherry pick of #1040 
Ref run from `cherry-pick-1040` branch
https://github.com/hiero-ledger/hiero-block-node/actions/runs/14525999682
=> chore: Cherry-pick of #1040 into release branch `release/0.9`

.github/workflows/local-node-test-reusable.yaml, .github/workflows/local-node-test.yaml
- quick fix for a failing build during the local node CI test
**UPDATE**:
- after fixing the build logic, I noticed also the logs were failing, that is fixed as well (wrong container name)
Closes #1091
=> fix: Local Node CI Tests Build Failure

block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
=> chore: Cherry pick 1136

docs/block-node/metrics.md
This document aims to add all defined metrics by the BlockNode App and it's default plugins.
For team members to access, this is the original spredsheeet where we worked and tracked the metrics with @jasperpotts 
https://docs.google.com/spreadsheets/d/16Pt55fydA_W1Fuk9B_GRpoyLpIOgOrzc3nZnkEhoTSk/edit?usp=sharing
Fixes #1131
=> docs: Add metrics document

protobuf/src/main/java/module-info.java
Changes:
- Adding Opens for all the required proto packages in consumer mode and publisher mode.
Fixes #1190
=> fix: Opening for reflection, so Simulator can run in Consumer mode using modules (Docker or K8s)

block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/app-core.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-access-service.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-node-service.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-historic.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-recent.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/messaging-facility.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/stream-publisher.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/stream-subscriber.json, block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/verification.json, block-node/app/docker/metrics/dashboards/block-node-server.json, block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java, block-node/block-providers/files.historic/build.gradle.kts, block-node/block-providers/files.historic/src/main/java/module-info.java, block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java, block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java, block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java, block-node/block-providers/files.recent/src/main/java/module-info.java, block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java, block-node/messaging/build.gradle.kts, block-node/messaging/src/main/java/module-info.java, block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/TestConfig.java, block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java, block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java, block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java, block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java, block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java, block-node/verification/src/main/java/org/hiero/block/node/verification/VerificationServicePlugin.java, charts/.gitignore, docs/block-node/metrics.md
Adding rest of the metrics to `0.11` version
=> chore: cherry-pick metric PRs into 0.11 release branch

docs/test-plan/template.md
Improved Test Plan Template.
Fixes #1287
=> chore: Improving Test Plan Template

block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java, block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java, block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java, protobuf-sources/src/main/proto/block-node/api/block_stream_subscribe_service.proto, protobuf-sources/src/main/proto/block-node/api/proof_service.proto, protobuf-sources/src/main/proto/block-node/api/state_service.proto, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/ConsumerStreamGrpcClientImplTest.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/ConsumerStreamObserverTest.java, tools-and-tests/suites/src/main/java/org/hiero/block/suites/subscriber/negative/NegativeSingleSubscriberTests.java
* Removed prefix values from enumerations
* Removed enumeration related to payment
* Adjusted references in code
Resolves #1057.
=> chore: #1057 remove prefixes from block node API enumerations

docs/design/persistence/block-node-retention-policy.md
- design documentation for Retention Policy
Resolves #1263
=> docs: Storage Retention Policy Design Documentation

docs/simulator/configuration.md, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/types/EndStreamMode.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/PublishStreamGrpcClient.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java, tools-and-tests/suites/src/main/java/module-info.java, tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
Introduce EndStream simulator publisher support
Fixes #1361
=> feat: Simulator Support for EndStream Request with Too_Far_Behind. so BN backfills

block-node/app/src/main/resources/logging.properties, block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java, block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java, block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java, block-node/verification/src/main/java/org/hiero/block/node/verification/VerificationServicePlugin.java
This PR is aimed at leave some TRACE level logs for helping troubleshoot and understand where an error happened when it happens. This unblocks other teams and our team, while trying to test CN2BN integration scenarios.
- Publisher Plugin was almost left out of more logging, due to separate tasks already covering this effort
- Persistence seems to have adequate logs already
- Added Needed logs for Verification Plugin
- Added some logs on messaging facility
- Added logs for server status request response
Fixes #1446 
Example of a normal flow logs:
```
2025-08-05 16:35:23.838-0600 FINE    BlocksFilesRecentPlugin#writeBlockToLivePath Wrote verified block: 9 to file: /Users/user/Projects/hiero-block-node/block-node/app/build/block-node-storage/files-live/000/000/000/000/000/0/000000000000000000 …
```
=> chore(logging): Improved Logging for debugging and troubleshooting at TRACE level.

docs/simulator/configuration.md, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java, tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java, tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java, tools-and-tests/suites/src/main/java/org/hiero/block/suites/BaseSuite.java, tools-and-tests/suites/src/main/java/org/hiero/block/suites/BlockNodeContainerConfig.java, tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java, tools-and-tests/suites/src/main/resources/block-nodes.json
- Add e2e scenario for On-Demand Happy path flow
- Add EndStream config and refactor simulator handling
- Enhance e2e docker containers
Fixes #1476
=> test: e2e scenario for On-Demand Happy path flow

block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java, block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
The stack trace when a remote entity closes a connection makes readers assume the block node crashed or something else is _wrong_.  This is a false assumption that wastes a lot of time explaining that a socket exception is a _normal_ client end-of-communication, so stop printing a stack trace in those cases.
=> chore: Remove stack trace from certain debug logs

block-node/health/src/main/java/org/hiero/block/node/health/HealthServicePlugin.java
* Added trace, info, and warning logs for success, non-success, and unexpected exception conditions, respectively.
=> chore: Add logs to health plugin

.github/workflows/solo-e2e-test.yml
This needs to be merged so it can be improved and tested on dispatch manually.
=> test(e2e-solo): Initial Version of E2E test using Solo, currently only on-dispatch.

.github/workflows/solo-e2e-test.yml
Add initial assertions to Solo E2E Test
=> test: add initial assertions Solo E2E Test

block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
* Clear the queueByMap on failed verficiations
* Added todos with considerations for upcoming changes
* Improved the handlerIsEnding method with a CAS for the next unstreamed
Fixes #1565
=> fix: Clear `queueByMap` When Verification Fails

block-node/app/docker/Dockerfile, block-node/app/docker/update-env.sh, block-node/health/src/main/java/org/hiero/block/node/health/HealthServicePlugin.java, block-node/messaging/src/main/java/org/hiero/block/node/messaging/MessagingConfig.java, block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java, block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java, block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java, block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/StreamPublisherPluginTest.java, block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java, block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java, charts/block-node-server/values-overrides/mid-size.yaml, charts/block-node-server/values-overrides/mini.yaml, charts/block-node-server/values.yaml, common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java, docs/block-node/configuration.md, protobuf-sources/build.gradle.kts, protobuf-sources/src/main/proto/internal/unparsed.proto
This PR aims to add several bug fixes to release `0.17.1` (upcoming) of BN to be used on integrations.
Adds the following PRs into this patch version, in the following order:
#1543 
#1544 
#1546 
#1558
#1564 
#1568 
#1570
=> fix(patch): Cherry picks for 0.17.1

docs/test-plan/publisher/stream-publisher-e2e-test-plan.md
* Added E2E test plan for the Multi-Publisher Plugin
Resolves #1418
=> test: Multi-Publisher Plugin E2E Test Plan

.github/workflows/solo-e2e-test.yml
- improved Solo commands and made it work with latest.
- updated default CN version to `0.65.0`
- Improved comments, addressed Todos, simplify version
- Added Assertions and Verifications
- Added Logs Recollection and Uploading to WF Run Summary
- Use solo version commands for `0.43.0` / latest but leaved `0.44` compatible commands as comments.
Fixes #1549
=> test(e2e-solo): Follow-up to GHA E2E Solo Test

.gitvote.yml
For more information: https://github.com/cncf/gitvote
=> chore: Create basic config file .gitvote.yml

.github/workflows/release-push-image.yaml, build.gradle.kts, charts/block-node-server/README.md, charts/blockstream-simulator/README.md
=> ci(publish): Cherry pick 1641

block-node/verification/src/main/java/org/hiero/block/node/verification/session/impl/ExtendedMerkleTreeVerificationSessionV0680.java, block-node/verification/src/test/java/org/hiero/block/node/verification/session/impl/ExtendedMerkleTreeVerificationSessionV0680Test.java
=> chore: Cherry pick 1731
